// Code generated by go-swagger; DO NOT EDIT.

package raid

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// DeleteDeviceTypeRaidReader is a Reader for the DeleteDeviceTypeRaid structure.
type DeleteDeviceTypeRaidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDeviceTypeRaidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDeviceTypeRaidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteDeviceTypeRaidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDeviceTypeRaidOK creates a DeleteDeviceTypeRaidOK with default headers values
func NewDeleteDeviceTypeRaidOK() *DeleteDeviceTypeRaidOK {
	return &DeleteDeviceTypeRaidOK{}
}

/* DeleteDeviceTypeRaidOK describes a response with status code 200, with default header values.

A DeleteDeviceTypeRaidResult is an response struct that is used to describe delete device type raid result.
*/
type DeleteDeviceTypeRaidOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DeleteDeviceTypeRaidOKBody
}

// IsSuccess returns true when this delete device type raid o k response has a 2xx status code
func (o *DeleteDeviceTypeRaidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete device type raid o k response has a 3xx status code
func (o *DeleteDeviceTypeRaidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete device type raid o k response has a 4xx status code
func (o *DeleteDeviceTypeRaidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete device type raid o k response has a 5xx status code
func (o *DeleteDeviceTypeRaidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete device type raid o k response a status code equal to that given
func (o *DeleteDeviceTypeRaidOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteDeviceTypeRaidOK) Error() string {
	return fmt.Sprintf("[DELETE /raids/deviceTypeRaid][%d] deleteDeviceTypeRaidOK  %+v", 200, o.Payload)
}

func (o *DeleteDeviceTypeRaidOK) String() string {
	return fmt.Sprintf("[DELETE /raids/deviceTypeRaid][%d] deleteDeviceTypeRaidOK  %+v", 200, o.Payload)
}

func (o *DeleteDeviceTypeRaidOK) GetPayload() *DeleteDeviceTypeRaidOKBody {
	return o.Payload
}

func (o *DeleteDeviceTypeRaidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DeleteDeviceTypeRaidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDeviceTypeRaidDefault creates a DeleteDeviceTypeRaidDefault with default headers values
func NewDeleteDeviceTypeRaidDefault(code int) *DeleteDeviceTypeRaidDefault {
	return &DeleteDeviceTypeRaidDefault{
		_statusCode: code,
	}
}

/* DeleteDeviceTypeRaidDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type DeleteDeviceTypeRaidDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DeleteDeviceTypeRaidDefaultBody
}

// Code gets the status code for the delete device type raid default response
func (o *DeleteDeviceTypeRaidDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete device type raid default response has a 2xx status code
func (o *DeleteDeviceTypeRaidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete device type raid default response has a 3xx status code
func (o *DeleteDeviceTypeRaidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete device type raid default response has a 4xx status code
func (o *DeleteDeviceTypeRaidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete device type raid default response has a 5xx status code
func (o *DeleteDeviceTypeRaidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete device type raid default response a status code equal to that given
func (o *DeleteDeviceTypeRaidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteDeviceTypeRaidDefault) Error() string {
	return fmt.Sprintf("[DELETE /raids/deviceTypeRaid][%d] deleteDeviceTypeRaid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDeviceTypeRaidDefault) String() string {
	return fmt.Sprintf("[DELETE /raids/deviceTypeRaid][%d] deleteDeviceTypeRaid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDeviceTypeRaidDefault) GetPayload() *DeleteDeviceTypeRaidDefaultBody {
	return o.Payload
}

func (o *DeleteDeviceTypeRaidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DeleteDeviceTypeRaidDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteDeviceTypeRaidDefaultBody delete device type raid default body
swagger:model DeleteDeviceTypeRaidDefaultBody
*/
type DeleteDeviceTypeRaidDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this delete device type raid default body
func (o *DeleteDeviceTypeRaidDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteDeviceTypeRaidDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("deleteDeviceTypeRaid default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *DeleteDeviceTypeRaidDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteDeviceTypeRaid default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteDeviceTypeRaid default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteDeviceTypeRaid default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete device type raid default body based on the context it is used
func (o *DeleteDeviceTypeRaidDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteDeviceTypeRaidDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteDeviceTypeRaid default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteDeviceTypeRaid default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteDeviceTypeRaidDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteDeviceTypeRaidDefaultBody) UnmarshalBinary(b []byte) error {
	var res DeleteDeviceTypeRaidDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteDeviceTypeRaidOKBody delete device type raid o k body
swagger:model DeleteDeviceTypeRaidOKBody
*/
type DeleteDeviceTypeRaidOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this delete device type raid o k body
func (o *DeleteDeviceTypeRaidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteDeviceTypeRaidOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteDeviceTypeRaidOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteDeviceTypeRaidOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete device type raid o k body based on the context it is used
func (o *DeleteDeviceTypeRaidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteDeviceTypeRaidOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteDeviceTypeRaidOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteDeviceTypeRaidOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteDeviceTypeRaidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteDeviceTypeRaidOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteDeviceTypeRaidOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
