// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// NewModifyLocalUserPasswordParams creates a new ModifyLocalUserPasswordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewModifyLocalUserPasswordParams() *ModifyLocalUserPasswordParams {
	return &ModifyLocalUserPasswordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewModifyLocalUserPasswordParamsWithTimeout creates a new ModifyLocalUserPasswordParams object
// with the ability to set a timeout on a request.
func NewModifyLocalUserPasswordParamsWithTimeout(timeout time.Duration) *ModifyLocalUserPasswordParams {
	return &ModifyLocalUserPasswordParams{
		timeout: timeout,
	}
}

// NewModifyLocalUserPasswordParamsWithContext creates a new ModifyLocalUserPasswordParams object
// with the ability to set a context for a request.
func NewModifyLocalUserPasswordParamsWithContext(ctx context.Context) *ModifyLocalUserPasswordParams {
	return &ModifyLocalUserPasswordParams{
		Context: ctx,
	}
}

// NewModifyLocalUserPasswordParamsWithHTTPClient creates a new ModifyLocalUserPasswordParams object
// with the ability to set a custom HTTPClient for a request.
func NewModifyLocalUserPasswordParamsWithHTTPClient(client *http.Client) *ModifyLocalUserPasswordParams {
	return &ModifyLocalUserPasswordParams{
		HTTPClient: client,
	}
}

/* ModifyLocalUserPasswordParams contains all the parameters to send to the API endpoint
   for the modify local user password operation.

   Typically these are written to a http.Request.
*/
type ModifyLocalUserPasswordParams struct {

	// Body.
	Body *models.ModifyUserPasswordRequest

	/* Authorization.

	   demo: curl -X GET -H "Authorization:Bearer wwabmrpdxz04qa10frpuw7key9qkd9bu" http://127.0.0.1:8801/v1/idcs 请使用个人自己创建apikey时候的token
	*/
	Authorization string

	/* BmpLanguage.

	   用户语言 [zh_CN, en_US]
	*/
	BmpLanguage *string

	/* BmpUserID.

	   用户uuid, deprecated
	*/
	BmpUserID *string

	/* TraceID.

	   流量唯一id
	*/
	TraceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the modify local user password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyLocalUserPasswordParams) WithDefaults() *ModifyLocalUserPasswordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the modify local user password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyLocalUserPasswordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithTimeout(timeout time.Duration) *ModifyLocalUserPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithContext(ctx context.Context) *ModifyLocalUserPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithHTTPClient(client *http.Client) *ModifyLocalUserPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithBody(body *models.ModifyUserPasswordRequest) *ModifyLocalUserPasswordParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetBody(body *models.ModifyUserPasswordRequest) {
	o.Body = body
}

// WithAuthorization adds the authorization to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithAuthorization(authorization string) *ModifyLocalUserPasswordParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBmpLanguage adds the bmpLanguage to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithBmpLanguage(bmpLanguage *string) *ModifyLocalUserPasswordParams {
	o.SetBmpLanguage(bmpLanguage)
	return o
}

// SetBmpLanguage adds the bmpLanguage to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetBmpLanguage(bmpLanguage *string) {
	o.BmpLanguage = bmpLanguage
}

// WithBmpUserID adds the bmpUserID to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithBmpUserID(bmpUserID *string) *ModifyLocalUserPasswordParams {
	o.SetBmpUserID(bmpUserID)
	return o
}

// SetBmpUserID adds the bmpUserId to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetBmpUserID(bmpUserID *string) {
	o.BmpUserID = bmpUserID
}

// WithTraceID adds the traceID to the modify local user password params
func (o *ModifyLocalUserPasswordParams) WithTraceID(traceID string) *ModifyLocalUserPasswordParams {
	o.SetTraceID(traceID)
	return o
}

// SetTraceID adds the traceId to the modify local user password params
func (o *ModifyLocalUserPasswordParams) SetTraceID(traceID string) {
	o.TraceID = traceID
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyLocalUserPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param authorization
	if err := r.SetHeaderParam("authorization", o.Authorization); err != nil {
		return err
	}

	if o.BmpLanguage != nil {

		// header param bmpLanguage
		if err := r.SetHeaderParam("bmpLanguage", *o.BmpLanguage); err != nil {
			return err
		}
	}

	if o.BmpUserID != nil {

		// header param bmpUserId
		if err := r.SetHeaderParam("bmpUserId", *o.BmpUserID); err != nil {
			return err
		}
	}

	// header param traceId
	if err := r.SetHeaderParam("traceId", o.TraceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
