// Code generated by go-swagger; DO NOT EDIT.

package sshkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// NewModifyUserSshkeyParams creates a new ModifyUserSshkeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewModifyUserSshkeyParams() *ModifyUserSshkeyParams {
	return &ModifyUserSshkeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewModifyUserSshkeyParamsWithTimeout creates a new ModifyUserSshkeyParams object
// with the ability to set a timeout on a request.
func NewModifyUserSshkeyParamsWithTimeout(timeout time.Duration) *ModifyUserSshkeyParams {
	return &ModifyUserSshkeyParams{
		timeout: timeout,
	}
}

// NewModifyUserSshkeyParamsWithContext creates a new ModifyUserSshkeyParams object
// with the ability to set a context for a request.
func NewModifyUserSshkeyParamsWithContext(ctx context.Context) *ModifyUserSshkeyParams {
	return &ModifyUserSshkeyParams{
		Context: ctx,
	}
}

// NewModifyUserSshkeyParamsWithHTTPClient creates a new ModifyUserSshkeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewModifyUserSshkeyParamsWithHTTPClient(client *http.Client) *ModifyUserSshkeyParams {
	return &ModifyUserSshkeyParams{
		HTTPClient: client,
	}
}

/* ModifyUserSshkeyParams contains all the parameters to send to the API endpoint
   for the modify user sshkey operation.

   Typically these are written to a http.Request.
*/
type ModifyUserSshkeyParams struct {

	// Body.
	Body *models.ModifySshkeyRequest

	/* Authorization.

	   demo: curl -X GET -H "Authorization:Bearer wwabmrpdxz04qa10frpuw7key9qkd9bu" http://127.0.0.1:8801/v1/idcs 请使用个人自己创建apikey时候的token
	*/
	Authorization string

	/* BmpLanguage.

	   用户语言 [zh_CN, en_US]
	*/
	BmpLanguage *string

	/* BmpUserID.

	   用户uuid
	*/
	BmpUserID *string

	// SshkeyID.
	SshkeyID string

	/* TraceID.

	   流量唯一id
	*/
	TraceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the modify user sshkey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyUserSshkeyParams) WithDefaults() *ModifyUserSshkeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the modify user sshkey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyUserSshkeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithTimeout(timeout time.Duration) *ModifyUserSshkeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithContext(ctx context.Context) *ModifyUserSshkeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithHTTPClient(client *http.Client) *ModifyUserSshkeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithBody(body *models.ModifySshkeyRequest) *ModifyUserSshkeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetBody(body *models.ModifySshkeyRequest) {
	o.Body = body
}

// WithAuthorization adds the authorization to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithAuthorization(authorization string) *ModifyUserSshkeyParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBmpLanguage adds the bmpLanguage to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithBmpLanguage(bmpLanguage *string) *ModifyUserSshkeyParams {
	o.SetBmpLanguage(bmpLanguage)
	return o
}

// SetBmpLanguage adds the bmpLanguage to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetBmpLanguage(bmpLanguage *string) {
	o.BmpLanguage = bmpLanguage
}

// WithBmpUserID adds the bmpUserID to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithBmpUserID(bmpUserID *string) *ModifyUserSshkeyParams {
	o.SetBmpUserID(bmpUserID)
	return o
}

// SetBmpUserID adds the bmpUserId to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetBmpUserID(bmpUserID *string) {
	o.BmpUserID = bmpUserID
}

// WithSshkeyID adds the sshkeyID to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithSshkeyID(sshkeyID string) *ModifyUserSshkeyParams {
	o.SetSshkeyID(sshkeyID)
	return o
}

// SetSshkeyID adds the sshkeyId to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetSshkeyID(sshkeyID string) {
	o.SshkeyID = sshkeyID
}

// WithTraceID adds the traceID to the modify user sshkey params
func (o *ModifyUserSshkeyParams) WithTraceID(traceID string) *ModifyUserSshkeyParams {
	o.SetTraceID(traceID)
	return o
}

// SetTraceID adds the traceId to the modify user sshkey params
func (o *ModifyUserSshkeyParams) SetTraceID(traceID string) {
	o.TraceID = traceID
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyUserSshkeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param authorization
	if err := r.SetHeaderParam("authorization", o.Authorization); err != nil {
		return err
	}

	if o.BmpLanguage != nil {

		// header param bmpLanguage
		if err := r.SetHeaderParam("bmpLanguage", *o.BmpLanguage); err != nil {
			return err
		}
	}

	if o.BmpUserID != nil {

		// header param bmpUserId
		if err := r.SetHeaderParam("bmpUserId", *o.BmpUserID); err != nil {
			return err
		}
	}

	// path param sshkey_id
	if err := r.SetPathParam("sshkey_id", o.SshkeyID); err != nil {
		return err
	}

	// header param traceId
	if err := r.SetHeaderParam("traceId", o.TraceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
