// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// VerifyUserReader is a Reader for the VerifyUser structure.
type VerifyUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VerifyUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVerifyUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVerifyUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVerifyUserOK creates a VerifyUserOK with default headers values
func NewVerifyUserOK() *VerifyUserOK {
	return &VerifyUserOK{}
}

/* VerifyUserOK describes a response with status code 200, with default header values.

A VerifyUserResult is an response struct that is used to describe verify user result.
*/
type VerifyUserOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *VerifyUserOKBody
}

// IsSuccess returns true when this verify user o k response has a 2xx status code
func (o *VerifyUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this verify user o k response has a 3xx status code
func (o *VerifyUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this verify user o k response has a 4xx status code
func (o *VerifyUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this verify user o k response has a 5xx status code
func (o *VerifyUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this verify user o k response a status code equal to that given
func (o *VerifyUserOK) IsCode(code int) bool {
	return code == 200
}

func (o *VerifyUserOK) Error() string {
	return fmt.Sprintf("[POST /users/verify][%d] verifyUserOK  %+v", 200, o.Payload)
}

func (o *VerifyUserOK) String() string {
	return fmt.Sprintf("[POST /users/verify][%d] verifyUserOK  %+v", 200, o.Payload)
}

func (o *VerifyUserOK) GetPayload() *VerifyUserOKBody {
	return o.Payload
}

func (o *VerifyUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(VerifyUserOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVerifyUserDefault creates a VerifyUserDefault with default headers values
func NewVerifyUserDefault(code int) *VerifyUserDefault {
	return &VerifyUserDefault{
		_statusCode: code,
	}
}

/* VerifyUserDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type VerifyUserDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *VerifyUserDefaultBody
}

// Code gets the status code for the verify user default response
func (o *VerifyUserDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this verify user default response has a 2xx status code
func (o *VerifyUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this verify user default response has a 3xx status code
func (o *VerifyUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this verify user default response has a 4xx status code
func (o *VerifyUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this verify user default response has a 5xx status code
func (o *VerifyUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this verify user default response a status code equal to that given
func (o *VerifyUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *VerifyUserDefault) Error() string {
	return fmt.Sprintf("[POST /users/verify][%d] verifyUser default  %+v", o._statusCode, o.Payload)
}

func (o *VerifyUserDefault) String() string {
	return fmt.Sprintf("[POST /users/verify][%d] verifyUser default  %+v", o._statusCode, o.Payload)
}

func (o *VerifyUserDefault) GetPayload() *VerifyUserDefaultBody {
	return o.Payload
}

func (o *VerifyUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(VerifyUserDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*VerifyUserDefaultBody verify user default body
swagger:model VerifyUserDefaultBody
*/
type VerifyUserDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this verify user default body
func (o *VerifyUserDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *VerifyUserDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("verifyUser default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *VerifyUserDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("verifyUser default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("verifyUser default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("verifyUser default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this verify user default body based on the context it is used
func (o *VerifyUserDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *VerifyUserDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("verifyUser default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("verifyUser default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *VerifyUserDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *VerifyUserDefaultBody) UnmarshalBinary(b []byte) error {
	var res VerifyUserDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*VerifyUserOKBody verify user o k body
swagger:model VerifyUserOKBody
*/
type VerifyUserOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this verify user o k body
func (o *VerifyUserOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *VerifyUserOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("verifyUserOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("verifyUserOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this verify user o k body based on the context it is used
func (o *VerifyUserOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *VerifyUserOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("verifyUserOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("verifyUserOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *VerifyUserOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *VerifyUserOKBody) UnmarshalBinary(b []byte) error {
	var res VerifyUserOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
