// Code generated by go-swagger; DO NOT EDIT.

package os

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// DescribeOSReader is a Reader for the DescribeOS structure.
type DescribeOSReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeOSReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeOSOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDescribeOSDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDescribeOSOK creates a DescribeOSOK with default headers values
func NewDescribeOSOK() *DescribeOSOK {
	return &DescribeOSOK{}
}

/* DescribeOSOK describes a response with status code 200, with default header values.

A DescribeOsResult is an response struct that is used to describe os.
*/
type DescribeOSOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DescribeOSOKBody
}

// IsSuccess returns true when this describe o s o k response has a 2xx status code
func (o *DescribeOSOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this describe o s o k response has a 3xx status code
func (o *DescribeOSOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe o s o k response has a 4xx status code
func (o *DescribeOSOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this describe o s o k response has a 5xx status code
func (o *DescribeOSOK) IsServerError() bool {
	return false
}

// IsCode returns true when this describe o s o k response a status code equal to that given
func (o *DescribeOSOK) IsCode(code int) bool {
	return code == 200
}

func (o *DescribeOSOK) Error() string {
	return fmt.Sprintf("[GET /oss/{os_id}][%d] describeOSOK  %+v", 200, o.Payload)
}

func (o *DescribeOSOK) String() string {
	return fmt.Sprintf("[GET /oss/{os_id}][%d] describeOSOK  %+v", 200, o.Payload)
}

func (o *DescribeOSOK) GetPayload() *DescribeOSOKBody {
	return o.Payload
}

func (o *DescribeOSOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DescribeOSOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeOSDefault creates a DescribeOSDefault with default headers values
func NewDescribeOSDefault(code int) *DescribeOSDefault {
	return &DescribeOSDefault{
		_statusCode: code,
	}
}

/* DescribeOSDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type DescribeOSDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DescribeOSDefaultBody
}

// Code gets the status code for the describe o s default response
func (o *DescribeOSDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this describe o s default response has a 2xx status code
func (o *DescribeOSDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this describe o s default response has a 3xx status code
func (o *DescribeOSDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this describe o s default response has a 4xx status code
func (o *DescribeOSDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this describe o s default response has a 5xx status code
func (o *DescribeOSDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this describe o s default response a status code equal to that given
func (o *DescribeOSDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DescribeOSDefault) Error() string {
	return fmt.Sprintf("[GET /oss/{os_id}][%d] describeOS default  %+v", o._statusCode, o.Payload)
}

func (o *DescribeOSDefault) String() string {
	return fmt.Sprintf("[GET /oss/{os_id}][%d] describeOS default  %+v", o._statusCode, o.Payload)
}

func (o *DescribeOSDefault) GetPayload() *DescribeOSDefaultBody {
	return o.Payload
}

func (o *DescribeOSDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DescribeOSDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DescribeOSDefaultBody describe o s default body
swagger:model DescribeOSDefaultBody
*/
type DescribeOSDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this describe o s default body
func (o *DescribeOSDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DescribeOSDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("describeOS default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *DescribeOSDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("describeOS default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("describeOS default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("describeOS default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this describe o s default body based on the context it is used
func (o *DescribeOSDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DescribeOSDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("describeOS default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("describeOS default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DescribeOSDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DescribeOSDefaultBody) UnmarshalBinary(b []byte) error {
	var res DescribeOSDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DescribeOSOKBody describe o s o k body
swagger:model DescribeOSOKBody
*/
type DescribeOSOKBody struct {

	// result
	Result *models.OsInfo `json:"result,omitempty"`
}

// Validate validates this describe o s o k body
func (o *DescribeOSOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DescribeOSOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("describeOSOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("describeOSOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this describe o s o k body based on the context it is used
func (o *DescribeOSOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DescribeOSOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("describeOSOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("describeOSOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DescribeOSOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DescribeOSOKBody) UnmarshalBinary(b []byte) error {
	var res DescribeOSOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
