// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// NewAssociatedDeviceTypeParams creates a new AssociatedDeviceTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssociatedDeviceTypeParams() *AssociatedDeviceTypeParams {
	return &AssociatedDeviceTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssociatedDeviceTypeParamsWithTimeout creates a new AssociatedDeviceTypeParams object
// with the ability to set a timeout on a request.
func NewAssociatedDeviceTypeParamsWithTimeout(timeout time.Duration) *AssociatedDeviceTypeParams {
	return &AssociatedDeviceTypeParams{
		timeout: timeout,
	}
}

// NewAssociatedDeviceTypeParamsWithContext creates a new AssociatedDeviceTypeParams object
// with the ability to set a context for a request.
func NewAssociatedDeviceTypeParamsWithContext(ctx context.Context) *AssociatedDeviceTypeParams {
	return &AssociatedDeviceTypeParams{
		Context: ctx,
	}
}

// NewAssociatedDeviceTypeParamsWithHTTPClient creates a new AssociatedDeviceTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssociatedDeviceTypeParamsWithHTTPClient(client *http.Client) *AssociatedDeviceTypeParams {
	return &AssociatedDeviceTypeParams{
		HTTPClient: client,
	}
}

/* AssociatedDeviceTypeParams contains all the parameters to send to the API endpoint
   for the associated device type operation.

   Typically these are written to a http.Request.
*/
type AssociatedDeviceTypeParams struct {

	// Body.
	Body *models.AssociateDeviceTypeRequest

	/* Authorization.

	   demo: curl -X GET -H "Authorization:Bearer wwabmrpdxz04qa10frpuw7key9qkd9bu" http://127.0.0.1:8801/v1/idcs 请使用个人自己创建apikey时候的token
	*/
	Authorization string

	/* BmpLanguage.

	   用户语言 [zh_CN, en_US]
	*/
	BmpLanguage *string

	/* BmpUserID.

	   用户uuid
	*/
	BmpUserID *string

	/* TraceID.

	   流量唯一id
	*/
	TraceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the associated device type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssociatedDeviceTypeParams) WithDefaults() *AssociatedDeviceTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the associated device type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssociatedDeviceTypeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the associated device type params
func (o *AssociatedDeviceTypeParams) WithTimeout(timeout time.Duration) *AssociatedDeviceTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the associated device type params
func (o *AssociatedDeviceTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the associated device type params
func (o *AssociatedDeviceTypeParams) WithContext(ctx context.Context) *AssociatedDeviceTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the associated device type params
func (o *AssociatedDeviceTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the associated device type params
func (o *AssociatedDeviceTypeParams) WithHTTPClient(client *http.Client) *AssociatedDeviceTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the associated device type params
func (o *AssociatedDeviceTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the associated device type params
func (o *AssociatedDeviceTypeParams) WithBody(body *models.AssociateDeviceTypeRequest) *AssociatedDeviceTypeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the associated device type params
func (o *AssociatedDeviceTypeParams) SetBody(body *models.AssociateDeviceTypeRequest) {
	o.Body = body
}

// WithAuthorization adds the authorization to the associated device type params
func (o *AssociatedDeviceTypeParams) WithAuthorization(authorization string) *AssociatedDeviceTypeParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the associated device type params
func (o *AssociatedDeviceTypeParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBmpLanguage adds the bmpLanguage to the associated device type params
func (o *AssociatedDeviceTypeParams) WithBmpLanguage(bmpLanguage *string) *AssociatedDeviceTypeParams {
	o.SetBmpLanguage(bmpLanguage)
	return o
}

// SetBmpLanguage adds the bmpLanguage to the associated device type params
func (o *AssociatedDeviceTypeParams) SetBmpLanguage(bmpLanguage *string) {
	o.BmpLanguage = bmpLanguage
}

// WithBmpUserID adds the bmpUserID to the associated device type params
func (o *AssociatedDeviceTypeParams) WithBmpUserID(bmpUserID *string) *AssociatedDeviceTypeParams {
	o.SetBmpUserID(bmpUserID)
	return o
}

// SetBmpUserID adds the bmpUserId to the associated device type params
func (o *AssociatedDeviceTypeParams) SetBmpUserID(bmpUserID *string) {
	o.BmpUserID = bmpUserID
}

// WithTraceID adds the traceID to the associated device type params
func (o *AssociatedDeviceTypeParams) WithTraceID(traceID string) *AssociatedDeviceTypeParams {
	o.SetTraceID(traceID)
	return o
}

// SetTraceID adds the traceId to the associated device type params
func (o *AssociatedDeviceTypeParams) SetTraceID(traceID string) {
	o.TraceID = traceID
}

// WriteToRequest writes these params to a swagger request
func (o *AssociatedDeviceTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param authorization
	if err := r.SetHeaderParam("authorization", o.Authorization); err != nil {
		return err
	}

	if o.BmpLanguage != nil {

		// header param bmpLanguage
		if err := r.SetHeaderParam("bmpLanguage", *o.BmpLanguage); err != nil {
			return err
		}
	}

	if o.BmpUserID != nil {

		// header param bmpUserId
		if err := r.SetHeaderParam("bmpUserId", *o.BmpUserID); err != nil {
			return err
		}
	}

	// header param traceId
	if err := r.SetHeaderParam("traceId", o.TraceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
