// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentStatusItem agent status item
//
// swagger:model AgentStatusItem
type AgentStatusItem struct {

	// agent version
	AgentVersion string `json:"agent_version,omitempty"`

	// instance ID
	InstanceID string `json:"instance_id,omitempty"`

	// s n
	SN string `json:"sn,omitempty"`

	// 1->running 2->stopped 0->unknown
	Status int64 `json:"status,omitempty"`

	// status 运行 停止 未知
	StatusName string `json:"statusName,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`
}

// Validate validates this agent status item
func (m *AgentStatusItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent status item based on context it is used
func (m *AgentStatusItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentStatusItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentStatusItem) UnmarshalBinary(b []byte) error {
	var res AgentStatusItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
