// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AssociateDeviceTypeRequest associate device type request
//
// swagger:model AssociateDeviceTypeRequest
type AssociateDeviceTypeRequest struct {

	// 设备类型id，数组，支持多个
	// Required: true
	DeviceTypeIDs []string `json:"deviceTypeIds"`

	// 镜像ID，
	// Required: true
	ImageID *string `json:"imageId"`
}

// Validate validates this associate device type request
func (m *AssociateDeviceTypeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceTypeIDs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AssociateDeviceTypeRequest) validateDeviceTypeIDs(formats strfmt.Registry) error {

	if err := validate.Required("deviceTypeIds", "body", m.DeviceTypeIDs); err != nil {
		return err
	}

	return nil
}

func (m *AssociateDeviceTypeRequest) validateImageID(formats strfmt.Registry) error {

	if err := validate.Required("imageId", "body", m.ImageID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this associate device type request based on context it is used
func (m *AssociateDeviceTypeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AssociateDeviceTypeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssociateDeviceTypeRequest) UnmarshalBinary(b []byte) error {
	var res AssociateDeviceTypeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
