// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeviceTypeID device type Id
//
// swagger:model DeviceTypeId
type DeviceTypeID struct {

	// 机型uuid
	// Required: true
	DeviceTypeID *string `json:"deviceTypeId"`
}

// Validate validates this device type Id
func (m *DeviceTypeID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceTypeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceTypeID) validateDeviceTypeID(formats strfmt.Registry) error {

	if err := validate.Required("deviceTypeId", "body", m.DeviceTypeID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this device type Id based on context it is used
func (m *DeviceTypeID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceTypeID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceTypeID) UnmarshalBinary(b []byte) error {
	var res DeviceTypeID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
