// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HasUnreadMessage has unread message
//
// swagger:model HasUnreadMessage
type HasUnreadMessage struct {

	// has unread
	HasUnread bool `json:"hasUnread,omitempty"`
}

// Validate validates this has unread message
func (m *HasUnreadMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this has unread message based on context it is used
func (m *HasUnreadMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HasUnreadMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HasUnreadMessage) UnmarshalBinary(b []byte) error {
	var res HasUnreadMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
