// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ImageID image Id
//
// swagger:model ImageId
type ImageID struct {

	// 镜像uuid
	ImageID string `json:"imageId,omitempty"`
}

// Validate validates this image Id
func (m *ImageID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image Id based on context it is used
func (m *ImageID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ImageID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageID) UnmarshalBinary(b []byte) error {
	var res ImageID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
