// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModifyUserRequest modify user request
//
// swagger:model ModifyUserRequest
type ModifyUserRequest struct {

	// 描述
	Description *string `json:"description,omitempty"`

	// 邮箱
	Email *string `json:"email,omitempty"`

	// 手机号
	PhoneNumber *string `json:"phoneNumber,omitempty"`

	// 国家地区码，如86
	PhonePrefix *string `json:"phonePrefix,omitempty"`
}

// Validate validates this modify user request
func (m *ModifyUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this modify user request based on context it is used
func (m *ModifyUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModifyUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModifyUserRequest) UnmarshalBinary(b []byte) error {
	var res ModifyUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
