// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReadMessagesRequest read messages request
//
// swagger:model ReadMessagesRequest
type ReadMessagesRequest struct {

	// message ids
	// Required: true
	MessageIds []string `json:"messageIds"`
}

// Validate validates this read messages request
func (m *ReadMessagesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessageIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReadMessagesRequest) validateMessageIds(formats strfmt.Registry) error {

	if err := validate.Required("messageIds", "body", m.MessageIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this read messages request based on context it is used
func (m *ReadMessagesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReadMessagesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReadMessagesRequest) UnmarshalBinary(b []byte) error {
	var res ReadMessagesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
