// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// SaveIsPushMailReader is a Reader for the SaveIsPushMail structure.
type SaveIsPushMailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SaveIsPushMailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSaveIsPushMailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSaveIsPushMailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSaveIsPushMailOK creates a SaveIsPushMailOK with default headers values
func NewSaveIsPushMailOK() *SaveIsPushMailOK {
	return &SaveIsPushMailOK{}
}

/* SaveIsPushMailOK describes a response with status code 200, with default header values.

A SaveIsPushMailResult is an response struct
*/
type SaveIsPushMailOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *SaveIsPushMailOKBody
}

// IsSuccess returns true when this save is push mail o k response has a 2xx status code
func (o *SaveIsPushMailOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this save is push mail o k response has a 3xx status code
func (o *SaveIsPushMailOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this save is push mail o k response has a 4xx status code
func (o *SaveIsPushMailOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this save is push mail o k response has a 5xx status code
func (o *SaveIsPushMailOK) IsServerError() bool {
	return false
}

// IsCode returns true when this save is push mail o k response a status code equal to that given
func (o *SaveIsPushMailOK) IsCode(code int) bool {
	return code == 200
}

func (o *SaveIsPushMailOK) Error() string {
	return fmt.Sprintf("[POST /messages/saveIsPushMail][%d] saveIsPushMailOK  %+v", 200, o.Payload)
}

func (o *SaveIsPushMailOK) String() string {
	return fmt.Sprintf("[POST /messages/saveIsPushMail][%d] saveIsPushMailOK  %+v", 200, o.Payload)
}

func (o *SaveIsPushMailOK) GetPayload() *SaveIsPushMailOKBody {
	return o.Payload
}

func (o *SaveIsPushMailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(SaveIsPushMailOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveIsPushMailDefault creates a SaveIsPushMailDefault with default headers values
func NewSaveIsPushMailDefault(code int) *SaveIsPushMailDefault {
	return &SaveIsPushMailDefault{
		_statusCode: code,
	}
}

/* SaveIsPushMailDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type SaveIsPushMailDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *SaveIsPushMailDefaultBody
}

// Code gets the status code for the save is push mail default response
func (o *SaveIsPushMailDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this save is push mail default response has a 2xx status code
func (o *SaveIsPushMailDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this save is push mail default response has a 3xx status code
func (o *SaveIsPushMailDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this save is push mail default response has a 4xx status code
func (o *SaveIsPushMailDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this save is push mail default response has a 5xx status code
func (o *SaveIsPushMailDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this save is push mail default response a status code equal to that given
func (o *SaveIsPushMailDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SaveIsPushMailDefault) Error() string {
	return fmt.Sprintf("[POST /messages/saveIsPushMail][%d] saveIsPushMail default  %+v", o._statusCode, o.Payload)
}

func (o *SaveIsPushMailDefault) String() string {
	return fmt.Sprintf("[POST /messages/saveIsPushMail][%d] saveIsPushMail default  %+v", o._statusCode, o.Payload)
}

func (o *SaveIsPushMailDefault) GetPayload() *SaveIsPushMailDefaultBody {
	return o.Payload
}

func (o *SaveIsPushMailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(SaveIsPushMailDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SaveIsPushMailDefaultBody save is push mail default body
swagger:model SaveIsPushMailDefaultBody
*/
type SaveIsPushMailDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this save is push mail default body
func (o *SaveIsPushMailDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SaveIsPushMailDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("saveIsPushMail default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *SaveIsPushMailDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("saveIsPushMail default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("saveIsPushMail default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("saveIsPushMail default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this save is push mail default body based on the context it is used
func (o *SaveIsPushMailDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SaveIsPushMailDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("saveIsPushMail default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("saveIsPushMail default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SaveIsPushMailDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SaveIsPushMailDefaultBody) UnmarshalBinary(b []byte) error {
	var res SaveIsPushMailDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SaveIsPushMailOKBody save is push mail o k body
swagger:model SaveIsPushMailOKBody
*/
type SaveIsPushMailOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this save is push mail o k body
func (o *SaveIsPushMailOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SaveIsPushMailOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("saveIsPushMailOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("saveIsPushMailOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this save is push mail o k body based on the context it is used
func (o *SaveIsPushMailOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SaveIsPushMailOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("saveIsPushMailOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("saveIsPushMailOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SaveIsPushMailOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SaveIsPushMailOKBody) UnmarshalBinary(b []byte) error {
	var res SaveIsPushMailOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
