// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LicenseToken license token
//
// swagger:model LicenseToken
type LicenseToken struct {

	// msg
	Msg string `json:"msg,omitempty"`
}

// Validate validates this license token
func (m *LicenseToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this license token based on context it is used
func (m *LicenseToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LicenseToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicenseToken) UnmarshalBinary(b []byte) error {
	var res LicenseToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
