// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModifyOSRequest modify o s request
//
// swagger:model ModifyOSRequest
type ModifyOSRequest struct {

	// 体系架构
	Architecture string `json:"architecture,omitempty"`

	// 位数
	Bits int64 `json:"bits,omitempty"`

	// 操作系统名称
	OsName string `json:"osName,omitempty"`

	// 操作系统平台
	OsType string `json:"osType,omitempty"`

	// 操作系统版本
	OsVersion string `json:"osVersion,omitempty"`

	// 系统用户
	SysUser string `json:"sysUser,omitempty"`
}

// Validate validates this modify o s request
func (m *ModifyOSRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this modify o s request based on context it is used
func (m *ModifyOSRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModifyOSRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModifyOSRequest) UnmarshalBinary(b []byte) error {
	var res ModifyOSRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
