// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectID project Id
//
// swagger:model ProjectId
type ProjectID struct {

	// 项目uuid
	ProjectID string `json:"projectId,omitempty"`
}

// Validate validates this project Id
func (m *ProjectID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this project Id based on context it is used
func (m *ProjectID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectID) UnmarshalBinary(b []byte) error {
	var res ProjectID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
