// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShareProject share project
//
// swagger:model ShareProject
type ShareProject struct {

	// 创建时间
	CreatedTime string `json:"createdTime,omitempty"`

	// 项目拥有者用户id
	OwnerUserID string `json:"ownerUserId,omitempty"`

	// 项目拥有者用户名
	OwnerUserName string `json:"ownerUserName,omitempty"`

	// 项目uuid
	ProjectID string `json:"projectId,omitempty"`

	// 项目名称
	ProjectName string `json:"projectName,omitempty"`

	// share projects
	ShareProjects []*ShareProject `json:"shareProjects"`

	// 项目共享者用户id
	SharedUserID string `json:"sharedUserId,omitempty"`

	// 项目拥有者用户名
	SharedUserName string `json:"sharedUserName,omitempty"`

	// 更新者
	UpdatedBy string `json:"updatedBy,omitempty"`

	// 更新时间
	UpdatedTime string `json:"updatedTime,omitempty"`
}

// Validate validates this share project
func (m *ShareProject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateShareProjects(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShareProject) validateShareProjects(formats strfmt.Registry) error {
	if swag.IsZero(m.ShareProjects) { // not required
		return nil
	}

	for i := 0; i < len(m.ShareProjects); i++ {
		if swag.IsZero(m.ShareProjects[i]) { // not required
			continue
		}

		if m.ShareProjects[i] != nil {
			if err := m.ShareProjects[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shareProjects" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("shareProjects" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this share project based on the context it is used
func (m *ShareProject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateShareProjects(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShareProject) contextValidateShareProjects(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ShareProjects); i++ {

		if m.ShareProjects[i] != nil {
			if err := m.ShareProjects[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shareProjects" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("shareProjects" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ShareProject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShareProject) UnmarshalBinary(b []byte) error {
	var res ShareProject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
