// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SshkeyList sshkey list
//
// swagger:model SshkeyList
type SshkeyList struct {

	// 页数
	PageNumber int64 `json:"pageNumber,omitempty"`

	// 页大小
	PageSize int64 `json:"pageSize,omitempty"`

	// sshkey实体列表
	Sshkeys []*Sshkey `json:"sshkeys"`

	// 总条数
	TotalCount int64 `json:"totalCount,omitempty"`
}

// Validate validates this sshkey list
func (m *SshkeyList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSshkeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SshkeyList) validateSshkeys(formats strfmt.Registry) error {
	if swag.IsZero(m.Sshkeys) { // not required
		return nil
	}

	for i := 0; i < len(m.Sshkeys); i++ {
		if swag.IsZero(m.Sshkeys[i]) { // not required
			continue
		}

		if m.Sshkeys[i] != nil {
			if err := m.Sshkeys[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sshkeys" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sshkeys" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sshkey list based on the context it is used
func (m *SshkeyList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSshkeys(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SshkeyList) contextValidateSshkeys(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Sshkeys); i++ {

		if m.Sshkeys[i] != nil {
			if err := m.Sshkeys[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sshkeys" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sshkeys" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SshkeyList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SshkeyList) UnmarshalBinary(b []byte) error {
	var res SshkeyList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
