// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateProjectRequest create project request
//
// swagger:model CreateProjectRequest
type CreateProjectRequest struct {

	// 是否作为该用户的默认项目, [0/1], 默认为0
	IsDefault int8 `json:"isDefault,omitempty"`

	// 是否作为系统项目, [0/1], 默认为0
	IsSystem int8 `json:"isSystem,omitempty"`

	// ProjectName 1~64字符，只支持数字、大小写字母、中英文下划线“_”及中划线“-”
	// Required: true
	ProjectName *string `json:"projectName"`
}

// Validate validates this create project request
func (m *CreateProjectRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProjectName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateProjectRequest) validateProjectName(formats strfmt.Registry) error {

	if err := validate.Required("projectName", "body", m.ProjectName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create project request based on context it is used
func (m *CreateProjectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateProjectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateProjectRequest) UnmarshalBinary(b []byte) error {
	var res CreateProjectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
