// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MoveProjectRequest move project request
//
// swagger:model MoveProjectRequest
type MoveProjectRequest struct {

	// to user_id
	// Required: true
	MoverID *string `json:"moverID"`

	// from user_id
	// Required: true
	OwnerID *string `json:"ownerID"`
}

// Validate validates this move project request
func (m *MoveProjectRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMoverID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwnerID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MoveProjectRequest) validateMoverID(formats strfmt.Registry) error {

	if err := validate.Required("moverID", "body", m.MoverID); err != nil {
		return err
	}

	return nil
}

func (m *MoveProjectRequest) validateOwnerID(formats strfmt.Registry) error {

	if err := validate.Required("ownerID", "body", m.OwnerID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this move project request based on context it is used
func (m *MoveProjectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MoveProjectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MoveProjectRequest) UnmarshalBinary(b []byte) error {
	var res MoveProjectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
