// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// User user
//
// swagger:model User
type User struct {

	// 创建者
	CreatedBy string `json:"createdBy,omitempty"`

	// 创建时间
	CreatedTime string `json:"createdTime,omitempty"`

	// 用户默认项目uuid
	DefaultProjectID string `json:"defaultProjectId,omitempty"`

	// 用户默认项目名称
	DefaultProjectName string `json:"defaultProjectName,omitempty"`

	// 描述
	Description string `json:"description,omitempty"`

	// 邮箱
	Email string `json:"email,omitempty"`

	// 用户id
	ID int64 `json:"id,omitempty"`

	// 默认语言（en_US/zh_CN）
	Language string `json:"language,omitempty"`

	// 手机号
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// 国家地区码，如86
	PhonePrefix string `json:"phonePrefix,omitempty"`

	// 角色uuid
	RoleID string `json:"roleId,omitempty"`

	// 角色名称
	RoleName string `json:"roleName,omitempty"`

	// 时区
	Timezone string `json:"timezone,omitempty"`

	// 更新者
	UpdatedBy string `json:"updatedBy,omitempty"`

	// 更新时间
	UpdatedTime string `json:"updatedTime,omitempty"`

	// 用户uuid
	UserID string `json:"userId,omitempty"`

	// 用户名，唯一
	UserName string `json:"userName,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user based on context it is used
func (m *User) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
