// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// RestartInstancesReader is a Reader for the RestartInstances structure.
type RestartInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestartInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestartInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestartInstancesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestartInstancesOK creates a RestartInstancesOK with default headers values
func NewRestartInstancesOK() *RestartInstancesOK {
	return &RestartInstancesOK{}
}

/* RestartInstancesOK describes a response with status code 200, with default header values.

A RestartInstancesResult is an response struct
*/
type RestartInstancesOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *RestartInstancesOKBody
}

// IsSuccess returns true when this restart instances o k response has a 2xx status code
func (o *RestartInstancesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this restart instances o k response has a 3xx status code
func (o *RestartInstancesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restart instances o k response has a 4xx status code
func (o *RestartInstancesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this restart instances o k response has a 5xx status code
func (o *RestartInstancesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this restart instances o k response a status code equal to that given
func (o *RestartInstancesOK) IsCode(code int) bool {
	return code == 200
}

func (o *RestartInstancesOK) Error() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:restartInstances][%d] restartInstancesOK  %+v", 200, o.Payload)
}

func (o *RestartInstancesOK) String() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:restartInstances][%d] restartInstancesOK  %+v", 200, o.Payload)
}

func (o *RestartInstancesOK) GetPayload() *RestartInstancesOKBody {
	return o.Payload
}

func (o *RestartInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(RestartInstancesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestartInstancesDefault creates a RestartInstancesDefault with default headers values
func NewRestartInstancesDefault(code int) *RestartInstancesDefault {
	return &RestartInstancesDefault{
		_statusCode: code,
	}
}

/* RestartInstancesDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type RestartInstancesDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *RestartInstancesDefaultBody
}

// Code gets the status code for the restart instances default response
func (o *RestartInstancesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this restart instances default response has a 2xx status code
func (o *RestartInstancesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this restart instances default response has a 3xx status code
func (o *RestartInstancesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this restart instances default response has a 4xx status code
func (o *RestartInstancesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this restart instances default response has a 5xx status code
func (o *RestartInstancesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this restart instances default response a status code equal to that given
func (o *RestartInstancesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RestartInstancesDefault) Error() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:restartInstances][%d] restartInstances default  %+v", o._statusCode, o.Payload)
}

func (o *RestartInstancesDefault) String() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:restartInstances][%d] restartInstances default  %+v", o._statusCode, o.Payload)
}

func (o *RestartInstancesDefault) GetPayload() *RestartInstancesDefaultBody {
	return o.Payload
}

func (o *RestartInstancesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(RestartInstancesDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*RestartInstancesDefaultBody restart instances default body
swagger:model RestartInstancesDefaultBody
*/
type RestartInstancesDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this restart instances default body
func (o *RestartInstancesDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RestartInstancesDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("restartInstances default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *RestartInstancesDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("restartInstances default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restartInstances default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restartInstances default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this restart instances default body based on the context it is used
func (o *RestartInstancesDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RestartInstancesDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restartInstances default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restartInstances default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RestartInstancesDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RestartInstancesDefaultBody) UnmarshalBinary(b []byte) error {
	var res RestartInstancesDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*RestartInstancesOKBody restart instances o k body
swagger:model RestartInstancesOKBody
*/
type RestartInstancesOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this restart instances o k body
func (o *RestartInstancesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RestartInstancesOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restartInstancesOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restartInstancesOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this restart instances o k body based on the context it is used
func (o *RestartInstancesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RestartInstancesOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("restartInstancesOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("restartInstancesOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RestartInstancesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RestartInstancesOKBody) UnmarshalBinary(b []byte) error {
	var res RestartInstancesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
