// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// StopProjectInstanceReader is a Reader for the StopProjectInstance structure.
type StopProjectInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopProjectInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopProjectInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStopProjectInstanceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStopProjectInstanceOK creates a StopProjectInstanceOK with default headers values
func NewStopProjectInstanceOK() *StopProjectInstanceOK {
	return &StopProjectInstanceOK{}
}

/* StopProjectInstanceOK describes a response with status code 200, with default header values.

A StopProjectInstanceResult is an response struct that is used to describe stop instance result.
*/
type StopProjectInstanceOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *StopProjectInstanceOKBody
}

// IsSuccess returns true when this stop project instance o k response has a 2xx status code
func (o *StopProjectInstanceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop project instance o k response has a 3xx status code
func (o *StopProjectInstanceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop project instance o k response has a 4xx status code
func (o *StopProjectInstanceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop project instance o k response has a 5xx status code
func (o *StopProjectInstanceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop project instance o k response a status code equal to that given
func (o *StopProjectInstanceOK) IsCode(code int) bool {
	return code == 200
}

func (o *StopProjectInstanceOK) Error() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}/stop][%d] stopProjectInstanceOK  %+v", 200, o.Payload)
}

func (o *StopProjectInstanceOK) String() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}/stop][%d] stopProjectInstanceOK  %+v", 200, o.Payload)
}

func (o *StopProjectInstanceOK) GetPayload() *StopProjectInstanceOKBody {
	return o.Payload
}

func (o *StopProjectInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(StopProjectInstanceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopProjectInstanceDefault creates a StopProjectInstanceDefault with default headers values
func NewStopProjectInstanceDefault(code int) *StopProjectInstanceDefault {
	return &StopProjectInstanceDefault{
		_statusCode: code,
	}
}

/* StopProjectInstanceDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type StopProjectInstanceDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *StopProjectInstanceDefaultBody
}

// Code gets the status code for the stop project instance default response
func (o *StopProjectInstanceDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this stop project instance default response has a 2xx status code
func (o *StopProjectInstanceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this stop project instance default response has a 3xx status code
func (o *StopProjectInstanceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this stop project instance default response has a 4xx status code
func (o *StopProjectInstanceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this stop project instance default response has a 5xx status code
func (o *StopProjectInstanceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this stop project instance default response a status code equal to that given
func (o *StopProjectInstanceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *StopProjectInstanceDefault) Error() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}/stop][%d] stopProjectInstance default  %+v", o._statusCode, o.Payload)
}

func (o *StopProjectInstanceDefault) String() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}/stop][%d] stopProjectInstance default  %+v", o._statusCode, o.Payload)
}

func (o *StopProjectInstanceDefault) GetPayload() *StopProjectInstanceDefaultBody {
	return o.Payload
}

func (o *StopProjectInstanceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(StopProjectInstanceDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*StopProjectInstanceDefaultBody stop project instance default body
swagger:model StopProjectInstanceDefaultBody
*/
type StopProjectInstanceDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this stop project instance default body
func (o *StopProjectInstanceDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopProjectInstanceDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("stopProjectInstance default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *StopProjectInstanceDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("stopProjectInstance default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopProjectInstance default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopProjectInstance default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this stop project instance default body based on the context it is used
func (o *StopProjectInstanceDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopProjectInstanceDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopProjectInstance default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopProjectInstance default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *StopProjectInstanceDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *StopProjectInstanceDefaultBody) UnmarshalBinary(b []byte) error {
	var res StopProjectInstanceDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*StopProjectInstanceOKBody stop project instance o k body
swagger:model StopProjectInstanceOKBody
*/
type StopProjectInstanceOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this stop project instance o k body
func (o *StopProjectInstanceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopProjectInstanceOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopProjectInstanceOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopProjectInstanceOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this stop project instance o k body based on the context it is used
func (o *StopProjectInstanceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopProjectInstanceOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopProjectInstanceOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopProjectInstanceOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *StopProjectInstanceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *StopProjectInstanceOKBody) UnmarshalBinary(b []byte) error {
	var res StopProjectInstanceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
