#!/bin/bash

curl -X PUT -H 'Authorization: JDCLOUD2-HMAC-SHA256 Credential=DD1B0BFA7BAA5DAED057ACF4817AF55B/20220424/cn-north-1/cps/jdcloud2_request, SignedHeaders=content-type;host;x-jdcloud-date;x-jdcloud-language;x-jdcloud-nonce;x-jdcloud-order-key;x-jdcloud-pin;x-jdcloud-profile, Signature=7fabd922cd7ed21259dd5aaa6a9598b71b5f3c26981df2130d7a4692331e31d6' -H 'Content-Type: application/json' -H 'User-Agent: JdcloudSdkGo/1.1.6 cps/2.5.5' -H 'X-Jdcloud-Date: 20220424T061849Z' -H 'X-Jdcloud-Language: cn' -H 'X-Jdcloud-Nonce: 288135bc-ba8b-4fc4-899a-1468bdc23331' -H 'X-Jdcloud-Order-Key: ghpmaezb-pz10-vodh-8x1g-bzu854815zfk' -H 'X-Jdcloud-Pin: MWMxODczMWZhYjdmNDkwNzg4MjM=' -H 'X-Jdcloud-Request-Id: ghpmaezb-pz10-vodh-8x1g-111111111111' -d '{
    "clientToken": null,
    "instanceSpec": {
        "aliasIps": null,
        "az": "cn-north-1a",
        "bandwidth": null,
        "bandwidthPackageId": null,
        "charge": {
            "autoRenew": false,
            "buyScenario": null,
            "chargeDuration": null,
            "chargeMode": "postpaid_by_duration",
            "chargeUnit": null
        },
        "cidr": null,
        "count": 1,
        "dataDiskPartitions": null,
        "dataRaidTypeId": "r-l6pounvfife0njlinhk6ztf2xyio",
        "description": null,
        "deviceType": "cps.s.normal",
        "enableInternet": "no",
        "enableIpv6": null,
        "extensionAliasIps": null,
        "extensionBandwidth": null,
        "extensionBandwidthPackageId": null,
        "extensionEnableInternet": null,
        "extensionEnableIpv6": null,
        "extensionInternetChargeMode": null,
        "extensionIpv6Address": null,
        "extensionIpv6AliasIps": null,
        "extensionLineType": null,
        "extensionPrivateIp": null,
        "extensionSubnetId": null,
        "hostname": null,
        "imageType": "standard",
        "interfaceMode": "bond",
        "internetChargeMode": null,
        "ipv6Address": null,
        "ipv6AliasIps": null,
        "keypairId": null,
        "keypairIdSos": null,
        "lineType": null,
        "name": "cccc",
        "networkType": "retail",
        "osTypeId": "i-v2xudi13m1yrdg3aencxya21bcaa",
        "password": "JDyun123",
        "privateIp": null,
        "resourceTags": null,
        "subnetId": null,
        "sysRaidTypeId": "r-wtzluqacgzzxgunnabdkpnpjew3d",
        "systemDiskPartitions": null,
        "userData": null
    },
    "regionId": "cn-north-1"
}' 'http://10.226.148.63:8000/v1/regions/cn-north-1/instances'
