// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-console-sdk/models"
)

// DeleteInstancesReader is a Reader for the DeleteInstances structure.
type DeleteInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteInstancesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteInstancesOK creates a DeleteInstancesOK with default headers values
func NewDeleteInstancesOK() *DeleteInstancesOK {
	return &DeleteInstancesOK{}
}

/* DeleteInstancesOK describes a response with status code 200, with default header values.

A DeleteInstancesResult is an response struct that is used to describe modify instance result.
*/
type DeleteInstancesOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DeleteInstancesOKBody
}

// IsSuccess returns true when this delete instances o k response has a 2xx status code
func (o *DeleteInstancesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete instances o k response has a 3xx status code
func (o *DeleteInstancesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete instances o k response has a 4xx status code
func (o *DeleteInstancesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete instances o k response has a 5xx status code
func (o *DeleteInstancesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete instances o k response a status code equal to that given
func (o *DeleteInstancesOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteInstancesOK) Error() string {
	return fmt.Sprintf("[DELETE /project/instances/batch/instances:deleteInstances][%d] deleteInstancesOK  %+v", 200, o.Payload)
}

func (o *DeleteInstancesOK) String() string {
	return fmt.Sprintf("[DELETE /project/instances/batch/instances:deleteInstances][%d] deleteInstancesOK  %+v", 200, o.Payload)
}

func (o *DeleteInstancesOK) GetPayload() *DeleteInstancesOKBody {
	return o.Payload
}

func (o *DeleteInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DeleteInstancesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteInstancesDefault creates a DeleteInstancesDefault with default headers values
func NewDeleteInstancesDefault(code int) *DeleteInstancesDefault {
	return &DeleteInstancesDefault{
		_statusCode: code,
	}
}

/* DeleteInstancesDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type DeleteInstancesDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DeleteInstancesDefaultBody
}

// Code gets the status code for the delete instances default response
func (o *DeleteInstancesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete instances default response has a 2xx status code
func (o *DeleteInstancesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete instances default response has a 3xx status code
func (o *DeleteInstancesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete instances default response has a 4xx status code
func (o *DeleteInstancesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete instances default response has a 5xx status code
func (o *DeleteInstancesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete instances default response a status code equal to that given
func (o *DeleteInstancesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteInstancesDefault) Error() string {
	return fmt.Sprintf("[DELETE /project/instances/batch/instances:deleteInstances][%d] deleteInstances default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteInstancesDefault) String() string {
	return fmt.Sprintf("[DELETE /project/instances/batch/instances:deleteInstances][%d] deleteInstances default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteInstancesDefault) GetPayload() *DeleteInstancesDefaultBody {
	return o.Payload
}

func (o *DeleteInstancesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DeleteInstancesDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteInstancesDefaultBody delete instances default body
swagger:model DeleteInstancesDefaultBody
*/
type DeleteInstancesDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this delete instances default body
func (o *DeleteInstancesDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteInstancesDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("deleteInstances default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *DeleteInstancesDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteInstances default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteInstances default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteInstances default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete instances default body based on the context it is used
func (o *DeleteInstancesDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteInstancesDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteInstances default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteInstances default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteInstancesDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteInstancesDefaultBody) UnmarshalBinary(b []byte) error {
	var res DeleteInstancesDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteInstancesOKBody delete instances o k body
swagger:model DeleteInstancesOKBody
*/
type DeleteInstancesOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this delete instances o k body
func (o *DeleteInstancesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteInstancesOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteInstancesOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteInstancesOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete instances o k body based on the context it is used
func (o *DeleteInstancesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteInstancesOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteInstancesOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteInstancesOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteInstancesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteInstancesOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteInstancesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
