// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-console-sdk/models"
)

// StopInstancesReader is a Reader for the StopInstances structure.
type StopInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStopInstancesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStopInstancesOK creates a StopInstancesOK with default headers values
func NewStopInstancesOK() *StopInstancesOK {
	return &StopInstancesOK{}
}

/* StopInstancesOK describes a response with status code 200, with default header values.

A StopInstancesResult is an response struct
*/
type StopInstancesOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *StopInstancesOKBody
}

// IsSuccess returns true when this stop instances o k response has a 2xx status code
func (o *StopInstancesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop instances o k response has a 3xx status code
func (o *StopInstancesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop instances o k response has a 4xx status code
func (o *StopInstancesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop instances o k response has a 5xx status code
func (o *StopInstancesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stop instances o k response a status code equal to that given
func (o *StopInstancesOK) IsCode(code int) bool {
	return code == 200
}

func (o *StopInstancesOK) Error() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:stopInstances][%d] stopInstancesOK  %+v", 200, o.Payload)
}

func (o *StopInstancesOK) String() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:stopInstances][%d] stopInstancesOK  %+v", 200, o.Payload)
}

func (o *StopInstancesOK) GetPayload() *StopInstancesOKBody {
	return o.Payload
}

func (o *StopInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(StopInstancesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopInstancesDefault creates a StopInstancesDefault with default headers values
func NewStopInstancesDefault(code int) *StopInstancesDefault {
	return &StopInstancesDefault{
		_statusCode: code,
	}
}

/* StopInstancesDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type StopInstancesDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *StopInstancesDefaultBody
}

// Code gets the status code for the stop instances default response
func (o *StopInstancesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this stop instances default response has a 2xx status code
func (o *StopInstancesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this stop instances default response has a 3xx status code
func (o *StopInstancesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this stop instances default response has a 4xx status code
func (o *StopInstancesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this stop instances default response has a 5xx status code
func (o *StopInstancesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this stop instances default response a status code equal to that given
func (o *StopInstancesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *StopInstancesDefault) Error() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:stopInstances][%d] stopInstances default  %+v", o._statusCode, o.Payload)
}

func (o *StopInstancesDefault) String() string {
	return fmt.Sprintf("[PUT /project/instances/batch/instances:stopInstances][%d] stopInstances default  %+v", o._statusCode, o.Payload)
}

func (o *StopInstancesDefault) GetPayload() *StopInstancesDefaultBody {
	return o.Payload
}

func (o *StopInstancesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(StopInstancesDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*StopInstancesDefaultBody stop instances default body
swagger:model StopInstancesDefaultBody
*/
type StopInstancesDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this stop instances default body
func (o *StopInstancesDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopInstancesDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("stopInstances default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *StopInstancesDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("stopInstances default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopInstances default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopInstances default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this stop instances default body based on the context it is used
func (o *StopInstancesDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopInstancesDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopInstances default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopInstances default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *StopInstancesDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *StopInstancesDefaultBody) UnmarshalBinary(b []byte) error {
	var res StopInstancesDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*StopInstancesOKBody stop instances o k body
swagger:model StopInstancesOKBody
*/
type StopInstancesOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this stop instances o k body
func (o *StopInstancesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopInstancesOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopInstancesOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopInstancesOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this stop instances o k body based on the context it is used
func (o *StopInstancesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *StopInstancesOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopInstancesOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stopInstancesOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *StopInstancesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *StopInstancesOKBody) UnmarshalBinary(b []byte) error {
	var res StopInstancesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
