// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// ModifyProjectInstanceReader is a Reader for the ModifyProjectInstance structure.
type ModifyProjectInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyProjectInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModifyProjectInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewModifyProjectInstanceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewModifyProjectInstanceOK creates a ModifyProjectInstanceOK with default headers values
func NewModifyProjectInstanceOK() *ModifyProjectInstanceOK {
	return &ModifyProjectInstanceOK{}
}

/* ModifyProjectInstanceOK describes a response with status code 200, with default header values.

A ModifyProjectInstanceResult is an response struct that is used to describe modify instance result.
*/
type ModifyProjectInstanceOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *ModifyProjectInstanceOKBody
}

// IsSuccess returns true when this modify project instance o k response has a 2xx status code
func (o *ModifyProjectInstanceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this modify project instance o k response has a 3xx status code
func (o *ModifyProjectInstanceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify project instance o k response has a 4xx status code
func (o *ModifyProjectInstanceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this modify project instance o k response has a 5xx status code
func (o *ModifyProjectInstanceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this modify project instance o k response a status code equal to that given
func (o *ModifyProjectInstanceOK) IsCode(code int) bool {
	return code == 200
}

func (o *ModifyProjectInstanceOK) Error() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}][%d] modifyProjectInstanceOK  %+v", 200, o.Payload)
}

func (o *ModifyProjectInstanceOK) String() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}][%d] modifyProjectInstanceOK  %+v", 200, o.Payload)
}

func (o *ModifyProjectInstanceOK) GetPayload() *ModifyProjectInstanceOKBody {
	return o.Payload
}

func (o *ModifyProjectInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(ModifyProjectInstanceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyProjectInstanceDefault creates a ModifyProjectInstanceDefault with default headers values
func NewModifyProjectInstanceDefault(code int) *ModifyProjectInstanceDefault {
	return &ModifyProjectInstanceDefault{
		_statusCode: code,
	}
}

/* ModifyProjectInstanceDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type ModifyProjectInstanceDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *ModifyProjectInstanceDefaultBody
}

// Code gets the status code for the modify project instance default response
func (o *ModifyProjectInstanceDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this modify project instance default response has a 2xx status code
func (o *ModifyProjectInstanceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this modify project instance default response has a 3xx status code
func (o *ModifyProjectInstanceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this modify project instance default response has a 4xx status code
func (o *ModifyProjectInstanceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this modify project instance default response has a 5xx status code
func (o *ModifyProjectInstanceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this modify project instance default response a status code equal to that given
func (o *ModifyProjectInstanceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ModifyProjectInstanceDefault) Error() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}][%d] modifyProjectInstance default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyProjectInstanceDefault) String() string {
	return fmt.Sprintf("[PUT /project/instances/{instance_id}][%d] modifyProjectInstance default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyProjectInstanceDefault) GetPayload() *ModifyProjectInstanceDefaultBody {
	return o.Payload
}

func (o *ModifyProjectInstanceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(ModifyProjectInstanceDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ModifyProjectInstanceDefaultBody modify project instance default body
swagger:model ModifyProjectInstanceDefaultBody
*/
type ModifyProjectInstanceDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this modify project instance default body
func (o *ModifyProjectInstanceDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyProjectInstanceDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("modifyProjectInstance default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *ModifyProjectInstanceDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("modifyProjectInstance default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyProjectInstance default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyProjectInstance default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this modify project instance default body based on the context it is used
func (o *ModifyProjectInstanceDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyProjectInstanceDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyProjectInstance default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyProjectInstance default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ModifyProjectInstanceDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyProjectInstanceDefaultBody) UnmarshalBinary(b []byte) error {
	var res ModifyProjectInstanceDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ModifyProjectInstanceOKBody modify project instance o k body
swagger:model ModifyProjectInstanceOKBody
*/
type ModifyProjectInstanceOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this modify project instance o k body
func (o *ModifyProjectInstanceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyProjectInstanceOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyProjectInstanceOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyProjectInstanceOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this modify project instance o k body based on the context it is used
func (o *ModifyProjectInstanceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyProjectInstanceOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyProjectInstanceOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyProjectInstanceOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ModifyProjectInstanceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyProjectInstanceOKBody) UnmarshalBinary(b []byte) error {
	var res ModifyProjectInstanceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
