// Code generated by go-swagger; DO NOT EDIT.

package raid

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// DeleteRaidReader is a Reader for the DeleteRaid structure.
type DeleteRaidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRaidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRaidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteRaidDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteRaidOK creates a DeleteRaidOK with default headers values
func NewDeleteRaidOK() *DeleteRaidOK {
	return &DeleteRaidOK{}
}

/* DeleteRaidOK describes a response with status code 200, with default header values.

A DeleteRaidResult is an response struct that is used to delete raid.
*/
type DeleteRaidOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DeleteRaidOKBody
}

// IsSuccess returns true when this delete raid o k response has a 2xx status code
func (o *DeleteRaidOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete raid o k response has a 3xx status code
func (o *DeleteRaidOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete raid o k response has a 4xx status code
func (o *DeleteRaidOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete raid o k response has a 5xx status code
func (o *DeleteRaidOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete raid o k response a status code equal to that given
func (o *DeleteRaidOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteRaidOK) Error() string {
	return fmt.Sprintf("[DELETE /raids/{raid_id}][%d] deleteRaidOK  %+v", 200, o.Payload)
}

func (o *DeleteRaidOK) String() string {
	return fmt.Sprintf("[DELETE /raids/{raid_id}][%d] deleteRaidOK  %+v", 200, o.Payload)
}

func (o *DeleteRaidOK) GetPayload() *DeleteRaidOKBody {
	return o.Payload
}

func (o *DeleteRaidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DeleteRaidOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRaidDefault creates a DeleteRaidDefault with default headers values
func NewDeleteRaidDefault(code int) *DeleteRaidDefault {
	return &DeleteRaidDefault{
		_statusCode: code,
	}
}

/* DeleteRaidDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type DeleteRaidDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *DeleteRaidDefaultBody
}

// Code gets the status code for the delete raid default response
func (o *DeleteRaidDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete raid default response has a 2xx status code
func (o *DeleteRaidDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete raid default response has a 3xx status code
func (o *DeleteRaidDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete raid default response has a 4xx status code
func (o *DeleteRaidDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete raid default response has a 5xx status code
func (o *DeleteRaidDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete raid default response a status code equal to that given
func (o *DeleteRaidDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteRaidDefault) Error() string {
	return fmt.Sprintf("[DELETE /raids/{raid_id}][%d] deleteRaid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteRaidDefault) String() string {
	return fmt.Sprintf("[DELETE /raids/{raid_id}][%d] deleteRaid default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteRaidDefault) GetPayload() *DeleteRaidDefaultBody {
	return o.Payload
}

func (o *DeleteRaidDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(DeleteRaidDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteRaidDefaultBody delete raid default body
swagger:model DeleteRaidDefaultBody
*/
type DeleteRaidDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this delete raid default body
func (o *DeleteRaidDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteRaidDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("deleteRaid default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *DeleteRaidDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteRaid default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteRaid default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteRaid default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete raid default body based on the context it is used
func (o *DeleteRaidDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteRaidDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteRaid default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteRaid default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRaidDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRaidDefaultBody) UnmarshalBinary(b []byte) error {
	var res DeleteRaidDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteRaidOKBody delete raid o k body
swagger:model DeleteRaidOKBody
*/
type DeleteRaidOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this delete raid o k body
func (o *DeleteRaidOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteRaidOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteRaidOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteRaidOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete raid o k body based on the context it is used
func (o *DeleteRaidOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteRaidOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteRaidOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("deleteRaidOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRaidOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRaidOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteRaidOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
