// Code generated by go-swagger; DO NOT EDIT.

package raid

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// NewModifyRaidParams creates a new ModifyRaidParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewModifyRaidParams() *ModifyRaidParams {
	return &ModifyRaidParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewModifyRaidParamsWithTimeout creates a new ModifyRaidParams object
// with the ability to set a timeout on a request.
func NewModifyRaidParamsWithTimeout(timeout time.Duration) *ModifyRaidParams {
	return &ModifyRaidParams{
		timeout: timeout,
	}
}

// NewModifyRaidParamsWithContext creates a new ModifyRaidParams object
// with the ability to set a context for a request.
func NewModifyRaidParamsWithContext(ctx context.Context) *ModifyRaidParams {
	return &ModifyRaidParams{
		Context: ctx,
	}
}

// NewModifyRaidParamsWithHTTPClient creates a new ModifyRaidParams object
// with the ability to set a custom HTTPClient for a request.
func NewModifyRaidParamsWithHTTPClient(client *http.Client) *ModifyRaidParams {
	return &ModifyRaidParams{
		HTTPClient: client,
	}
}

/* ModifyRaidParams contains all the parameters to send to the API endpoint
   for the modify raid operation.

   Typically these are written to a http.Request.
*/
type ModifyRaidParams struct {

	// Body.
	Body *models.ModifyRaidRequest

	/* Authorization.

	   demo: curl -X GET -H "Authorization:Bearer wwabmrpdxz04qa10frpuw7key9qkd9bu" http://127.0.0.1:8801/v1/idcs 请使用个人自己创建apikey时候的token
	*/
	Authorization string

	/* BmpLanguage.

	   用户语言 [zh_CN, en_US]
	*/
	BmpLanguage *string

	/* BmpUserID.

	   用户uuid
	*/
	BmpUserID *string

	// RaidID.
	RaidID string

	/* TraceID.

	   流量唯一id
	*/
	TraceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the modify raid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyRaidParams) WithDefaults() *ModifyRaidParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the modify raid params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyRaidParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the modify raid params
func (o *ModifyRaidParams) WithTimeout(timeout time.Duration) *ModifyRaidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify raid params
func (o *ModifyRaidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify raid params
func (o *ModifyRaidParams) WithContext(ctx context.Context) *ModifyRaidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify raid params
func (o *ModifyRaidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify raid params
func (o *ModifyRaidParams) WithHTTPClient(client *http.Client) *ModifyRaidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify raid params
func (o *ModifyRaidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify raid params
func (o *ModifyRaidParams) WithBody(body *models.ModifyRaidRequest) *ModifyRaidParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify raid params
func (o *ModifyRaidParams) SetBody(body *models.ModifyRaidRequest) {
	o.Body = body
}

// WithAuthorization adds the authorization to the modify raid params
func (o *ModifyRaidParams) WithAuthorization(authorization string) *ModifyRaidParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the modify raid params
func (o *ModifyRaidParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBmpLanguage adds the bmpLanguage to the modify raid params
func (o *ModifyRaidParams) WithBmpLanguage(bmpLanguage *string) *ModifyRaidParams {
	o.SetBmpLanguage(bmpLanguage)
	return o
}

// SetBmpLanguage adds the bmpLanguage to the modify raid params
func (o *ModifyRaidParams) SetBmpLanguage(bmpLanguage *string) {
	o.BmpLanguage = bmpLanguage
}

// WithBmpUserID adds the bmpUserID to the modify raid params
func (o *ModifyRaidParams) WithBmpUserID(bmpUserID *string) *ModifyRaidParams {
	o.SetBmpUserID(bmpUserID)
	return o
}

// SetBmpUserID adds the bmpUserId to the modify raid params
func (o *ModifyRaidParams) SetBmpUserID(bmpUserID *string) {
	o.BmpUserID = bmpUserID
}

// WithRaidID adds the raidID to the modify raid params
func (o *ModifyRaidParams) WithRaidID(raidID string) *ModifyRaidParams {
	o.SetRaidID(raidID)
	return o
}

// SetRaidID adds the raidId to the modify raid params
func (o *ModifyRaidParams) SetRaidID(raidID string) {
	o.RaidID = raidID
}

// WithTraceID adds the traceID to the modify raid params
func (o *ModifyRaidParams) WithTraceID(traceID string) *ModifyRaidParams {
	o.SetTraceID(traceID)
	return o
}

// SetTraceID adds the traceId to the modify raid params
func (o *ModifyRaidParams) SetTraceID(traceID string) {
	o.TraceID = traceID
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyRaidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param authorization
	if err := r.SetHeaderParam("authorization", o.Authorization); err != nil {
		return err
	}

	if o.BmpLanguage != nil {

		// header param bmpLanguage
		if err := r.SetHeaderParam("bmpLanguage", *o.BmpLanguage); err != nil {
			return err
		}
	}

	if o.BmpUserID != nil {

		// header param bmpUserId
		if err := r.SetHeaderParam("bmpUserId", *o.BmpUserID); err != nil {
			return err
		}
	}

	// path param raid_id
	if err := r.SetPathParam("raid_id", o.RaidID); err != nil {
		return err
	}

	// header param traceId
	if err := r.SetHeaderParam("traceId", o.TraceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
