// Code generated by go-swagger; DO NOT EDIT.

package monitor_proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDesrcibeTagsParams creates a new DesrcibeTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDesrcibeTagsParams() *DesrcibeTagsParams {
	return &DesrcibeTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDesrcibeTagsParamsWithTimeout creates a new DesrcibeTagsParams object
// with the ability to set a timeout on a request.
func NewDesrcibeTagsParamsWithTimeout(timeout time.Duration) *DesrcibeTagsParams {
	return &DesrcibeTagsParams{
		timeout: timeout,
	}
}

// NewDesrcibeTagsParamsWithContext creates a new DesrcibeTagsParams object
// with the ability to set a context for a request.
func NewDesrcibeTagsParamsWithContext(ctx context.Context) *DesrcibeTagsParams {
	return &DesrcibeTagsParams{
		Context: ctx,
	}
}

// NewDesrcibeTagsParamsWithHTTPClient creates a new DesrcibeTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDesrcibeTagsParamsWithHTTPClient(client *http.Client) *DesrcibeTagsParams {
	return &DesrcibeTagsParams{
		HTTPClient: client,
	}
}

/* DesrcibeTagsParams contains all the parameters to send to the API endpoint
   for the desrcibe tags operation.

   Typically these are written to a http.Request.
*/
type DesrcibeTagsParams struct {

	/* Authorization.

	   demo: curl -X GET -H "Authorization:Bearer wwabmrpdxz04qa10frpuw7key9qkd9bu" http://127.0.0.1:8801/v1/idcs 请使用个人自己创建apikey时候的token
	*/
	Authorization string

	/* BmpLanguage.

	   用户语言 [zh_CN, en_US]
	*/
	BmpLanguage *string

	/* BmpUserID.

	   用户uuid, deprecated
	*/
	BmpUserID *string

	/* InstanceID.

	   instanceId
	*/
	InstanceID string

	/* TagName.

	   tagName [disk mountpoint nic]
	*/
	TagName string

	/* TraceID.

	   流量唯一id
	*/
	TraceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the desrcibe tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DesrcibeTagsParams) WithDefaults() *DesrcibeTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the desrcibe tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DesrcibeTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the desrcibe tags params
func (o *DesrcibeTagsParams) WithTimeout(timeout time.Duration) *DesrcibeTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the desrcibe tags params
func (o *DesrcibeTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the desrcibe tags params
func (o *DesrcibeTagsParams) WithContext(ctx context.Context) *DesrcibeTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the desrcibe tags params
func (o *DesrcibeTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the desrcibe tags params
func (o *DesrcibeTagsParams) WithHTTPClient(client *http.Client) *DesrcibeTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the desrcibe tags params
func (o *DesrcibeTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the desrcibe tags params
func (o *DesrcibeTagsParams) WithAuthorization(authorization string) *DesrcibeTagsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the desrcibe tags params
func (o *DesrcibeTagsParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBmpLanguage adds the bmpLanguage to the desrcibe tags params
func (o *DesrcibeTagsParams) WithBmpLanguage(bmpLanguage *string) *DesrcibeTagsParams {
	o.SetBmpLanguage(bmpLanguage)
	return o
}

// SetBmpLanguage adds the bmpLanguage to the desrcibe tags params
func (o *DesrcibeTagsParams) SetBmpLanguage(bmpLanguage *string) {
	o.BmpLanguage = bmpLanguage
}

// WithBmpUserID adds the bmpUserID to the desrcibe tags params
func (o *DesrcibeTagsParams) WithBmpUserID(bmpUserID *string) *DesrcibeTagsParams {
	o.SetBmpUserID(bmpUserID)
	return o
}

// SetBmpUserID adds the bmpUserId to the desrcibe tags params
func (o *DesrcibeTagsParams) SetBmpUserID(bmpUserID *string) {
	o.BmpUserID = bmpUserID
}

// WithInstanceID adds the instanceID to the desrcibe tags params
func (o *DesrcibeTagsParams) WithInstanceID(instanceID string) *DesrcibeTagsParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the desrcibe tags params
func (o *DesrcibeTagsParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithTagName adds the tagName to the desrcibe tags params
func (o *DesrcibeTagsParams) WithTagName(tagName string) *DesrcibeTagsParams {
	o.SetTagName(tagName)
	return o
}

// SetTagName adds the tagName to the desrcibe tags params
func (o *DesrcibeTagsParams) SetTagName(tagName string) {
	o.TagName = tagName
}

// WithTraceID adds the traceID to the desrcibe tags params
func (o *DesrcibeTagsParams) WithTraceID(traceID string) *DesrcibeTagsParams {
	o.SetTraceID(traceID)
	return o
}

// SetTraceID adds the traceId to the desrcibe tags params
func (o *DesrcibeTagsParams) SetTraceID(traceID string) {
	o.TraceID = traceID
}

// WriteToRequest writes these params to a swagger request
func (o *DesrcibeTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param authorization
	if err := r.SetHeaderParam("authorization", o.Authorization); err != nil {
		return err
	}

	if o.BmpLanguage != nil {

		// header param bmpLanguage
		if err := r.SetHeaderParam("bmpLanguage", *o.BmpLanguage); err != nil {
			return err
		}
	}

	if o.BmpUserID != nil {

		// header param bmpUserId
		if err := r.SetHeaderParam("bmpUserId", *o.BmpUserID); err != nil {
			return err
		}
	}

	// query param instanceId
	qrInstanceID := o.InstanceID
	qInstanceID := qrInstanceID
	if qInstanceID != "" {

		if err := r.SetQueryParam("instanceId", qInstanceID); err != nil {
			return err
		}
	}

	// query param tagName
	qrTagName := o.TagName
	qTagName := qrTagName
	if qTagName != "" {

		if err := r.SetQueryParam("tagName", qTagName); err != nil {
			return err
		}
	}

	// header param traceId
	if err := r.SetHeaderParam("traceId", o.TraceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
