// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-sdk/models"
)

// RemoveDeviceReader is a Reader for the RemoveDevice structure.
type RemoveDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRemoveDeviceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRemoveDeviceOK creates a RemoveDeviceOK with default headers values
func NewRemoveDeviceOK() *RemoveDeviceOK {
	return &RemoveDeviceOK{}
}

/* RemoveDeviceOK describes a response with status code 200, with default header values.

A RemoveDeviceResult is an response struct that is used to describe restart instance result.
*/
type RemoveDeviceOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *RemoveDeviceOKBody
}

// IsSuccess returns true when this remove device o k response has a 2xx status code
func (o *RemoveDeviceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove device o k response has a 3xx status code
func (o *RemoveDeviceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove device o k response has a 4xx status code
func (o *RemoveDeviceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove device o k response has a 5xx status code
func (o *RemoveDeviceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this remove device o k response a status code equal to that given
func (o *RemoveDeviceOK) IsCode(code int) bool {
	return code == 200
}

func (o *RemoveDeviceOK) Error() string {
	return fmt.Sprintf("[PUT /devices/{device_id}/remove][%d] removeDeviceOK  %+v", 200, o.Payload)
}

func (o *RemoveDeviceOK) String() string {
	return fmt.Sprintf("[PUT /devices/{device_id}/remove][%d] removeDeviceOK  %+v", 200, o.Payload)
}

func (o *RemoveDeviceOK) GetPayload() *RemoveDeviceOKBody {
	return o.Payload
}

func (o *RemoveDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(RemoveDeviceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveDeviceDefault creates a RemoveDeviceDefault with default headers values
func NewRemoveDeviceDefault(code int) *RemoveDeviceDefault {
	return &RemoveDeviceDefault{
		_statusCode: code,
	}
}

/* RemoveDeviceDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type RemoveDeviceDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *RemoveDeviceDefaultBody
}

// Code gets the status code for the remove device default response
func (o *RemoveDeviceDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this remove device default response has a 2xx status code
func (o *RemoveDeviceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this remove device default response has a 3xx status code
func (o *RemoveDeviceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this remove device default response has a 4xx status code
func (o *RemoveDeviceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this remove device default response has a 5xx status code
func (o *RemoveDeviceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this remove device default response a status code equal to that given
func (o *RemoveDeviceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *RemoveDeviceDefault) Error() string {
	return fmt.Sprintf("[PUT /devices/{device_id}/remove][%d] removeDevice default  %+v", o._statusCode, o.Payload)
}

func (o *RemoveDeviceDefault) String() string {
	return fmt.Sprintf("[PUT /devices/{device_id}/remove][%d] removeDevice default  %+v", o._statusCode, o.Payload)
}

func (o *RemoveDeviceDefault) GetPayload() *RemoveDeviceDefaultBody {
	return o.Payload
}

func (o *RemoveDeviceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(RemoveDeviceDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*RemoveDeviceDefaultBody remove device default body
swagger:model RemoveDeviceDefaultBody
*/
type RemoveDeviceDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this remove device default body
func (o *RemoveDeviceDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RemoveDeviceDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("removeDevice default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *RemoveDeviceDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("removeDevice default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("removeDevice default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("removeDevice default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this remove device default body based on the context it is used
func (o *RemoveDeviceDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RemoveDeviceDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("removeDevice default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("removeDevice default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RemoveDeviceDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RemoveDeviceDefaultBody) UnmarshalBinary(b []byte) error {
	var res RemoveDeviceDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*RemoveDeviceOKBody remove device o k body
swagger:model RemoveDeviceOKBody
*/
type RemoveDeviceOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this remove device o k body
func (o *RemoveDeviceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RemoveDeviceOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("removeDeviceOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("removeDeviceOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this remove device o k body based on the context it is used
func (o *RemoveDeviceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RemoveDeviceOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("removeDeviceOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("removeDeviceOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RemoveDeviceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RemoveDeviceOKBody) UnmarshalBinary(b []byte) error {
	var res RemoveDeviceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
