package bmpRules

const (
	//BMP_METRIC_NAME = "bmp_monitor"
	ALERT_NAME_TEMPLATE = "%v_%v_%v_%v_%v" // source_alarmId_instanceId_metricname_device
	ALERT_EXPR_DEVICE = "%v{instance_id=\"%v\",metric_name=\"%v\",device=\"%v\"}"
	ALERT_EXPR_DEVICE_WITHOUT = "%v{instance_id=\"%v\",metric_name=\"%v\"}"

	SAMPLE_DEFAULT_METHOD_TMP = "rate(%v[%v])"

	ALERT_EXPR_METHOD_MAX = "max"
	ALERT_EXPR_METHOD_MIN = "min"
	ALERT_EXPR_METHOD_SUM = "sum"
	ALERT_EXPR_METHOD_AVG = "avg"

	ALERT_EXPR_OPERATOR_GT = ">"
	ALERT_EXPR_OPERATOR_GT_CODE = "gt"
	ALERT_EXPR_OPERATOR_GTE = ">="
	ALERT_EXPR_OPERATOR_GTE_CODE = "gte"
	ALERT_EXPR_OPERATOR_LT = "<"
	ALERT_EXPR_OPERATOR_LT_CODE = "lt"
	ALERT_EXPR_OPERATOR_LTE = "<="
	ALERT_EXPR_OPERATOR_LTE_CODE = "lte"
	ALERT_EXPR_OPERATOR_EQ = "=="
	ALERT_EXPR_OPERATOR_EQ_CODE = "eq"
	ALERT_EXPR_OPERATOR_NEQ = "!="
	ALERT_EXPR_OPERATOR_NEQ_CODE = "neq"

	//通知周期 5|10|15|30|60|180|360|720|1440
	NOTICE_PERIOD_5 = 5
	NOTICE_PERIOD_5_LABEL = "NoticePeriod-5m"
	NOTICE_PERIOD_10 = 10
	NOTICE_PERIOD_10_LABEL = "NoticePeriod-10m"
	NOTICE_PERIOD_15 = 15
	NOTICE_PERIOD_15_LABEL = "NoticePeriod-15m"
	NOTICE_PERIOD_30 = 30
	NOTICE_PERIOD_30_LABEL = "NoticePeriod-30m"
	NOTICE_PERIOD_60 = 60
	NOTICE_PERIOD_60_LABEL = "NoticePeriod-60m"
	NOTICE_PERIOD_180 = 180
	NOTICE_PERIOD_180_LABEL = "NoticePeriod-180m"
	NOTICE_PERIOD_720 = 720
	NOTICE_PERIOD_720_LABEL = "NoticePeriod-720m"
	NOTICE_PERIOD_1440 = 1440
	NOTICE_PERIOD_1440_LABEL = "NoticePeriod-1440m"

	CUSTOM_LABELS_NOTICE_PERIOD = "noticePeriodLabel"
	CUSTOM_BMPLABELS_RULEID = "ruleId"
	CUSTOM_BMPLABELS_INSTANCEID = "instanceId"
	CUSTOM_BMPLABELS_CURRENTVALUE = "currentValue"
	CUSTOM_BMPLABELS_METRIC = "metric"
	CUSTOM_BMPLABELS_CALCULATION = "calculation"
	CUSTOM_BMPLABELS_CALCULATION_UNIT = "calculationUnit"
	CUSTOM_BMPLABELS_PERIOD = "period"
	CUSTOM_BMPLABELS_TIMES = "times"
	CUSTOM_BMPLABELS_NOTICELEVEL = "noticeLevel"
	CUSTOM_BMPLABELS_THRESHOID = "threshold"
	CUSTOM_BMPLABELS_OPERATION = "operation"

	SYSTEM_BMPLABELS_ALERTNAME = "alertname"

	//需要rate计算的指标
	RATE_METRIC_DISK_READ = "bmp.disk.counts.read"
	RATE_METRIC_DISK_WRITE = "bmp.disk.counts.write"
	RATE_METRIC_NETWORK_INGRESS = "bmp.network.packets.ingress"
	RATE_METRIC_NETWORK_EGRESS = "bmp.network.packets.egress"
	RATE_METRIC_DISK_BYTESREAD = "bmp.disk.bytes.read"
	RATE_METRIC_DISK_BYTESWRITE = "bmp.disk.bytes.write"
	RATE_METRIC_NETWORK_BYTEINGRESS = "bmp.network.bytes.ingress"
	RATE_METRIC_NETWORK_BYTEEGRESS =  "bmp.network.bytes.egress"

)

var AlertExprOperatorMap = map[string]string {
	ALERT_EXPR_OPERATOR_GT       : ALERT_EXPR_OPERATOR_GT,
	ALERT_EXPR_OPERATOR_GT_CODE  : ALERT_EXPR_OPERATOR_GT,
	ALERT_EXPR_OPERATOR_GTE      : ALERT_EXPR_OPERATOR_GTE,
	ALERT_EXPR_OPERATOR_GTE_CODE : ALERT_EXPR_OPERATOR_GTE,
	ALERT_EXPR_OPERATOR_LT       : ALERT_EXPR_OPERATOR_LT,
	ALERT_EXPR_OPERATOR_LT_CODE  : ALERT_EXPR_OPERATOR_LT,
	ALERT_EXPR_OPERATOR_LTE      : ALERT_EXPR_OPERATOR_LTE,
	ALERT_EXPR_OPERATOR_LTE_CODE : ALERT_EXPR_OPERATOR_LTE,
	ALERT_EXPR_OPERATOR_EQ       : ALERT_EXPR_OPERATOR_EQ,
	ALERT_EXPR_OPERATOR_EQ_CODE  : ALERT_EXPR_OPERATOR_EQ,
	ALERT_EXPR_OPERATOR_NEQ      : ALERT_EXPR_OPERATOR_NEQ,
	ALERT_EXPR_OPERATOR_NEQ_CODE : ALERT_EXPR_OPERATOR_NEQ,
}

var AlertExprMethodMap = map[string]string {
	ALERT_EXPR_METHOD_MAX : "max(%v)",
	ALERT_EXPR_METHOD_MIN : "min(%v)",
	ALERT_EXPR_METHOD_SUM : "sum(%v)",
	ALERT_EXPR_METHOD_AVG : "avg(%v)",
}

var NoticePeriodMap = map[int]string {
	NOTICE_PERIOD_5  : NOTICE_PERIOD_5_LABEL,
	NOTICE_PERIOD_10 : NOTICE_PERIOD_10_LABEL,
	NOTICE_PERIOD_15 : NOTICE_PERIOD_15_LABEL,
	NOTICE_PERIOD_30 : NOTICE_PERIOD_30_LABEL,
	NOTICE_PERIOD_60 : NOTICE_PERIOD_60_LABEL,
	NOTICE_PERIOD_180: NOTICE_PERIOD_180_LABEL,
	NOTICE_PERIOD_720: NOTICE_PERIOD_720_LABEL,
	NOTICE_PERIOD_1440 : NOTICE_PERIOD_1440_LABEL,
}

var SampleDefaultMethodMap = map[string]string {
	RATE_METRIC_DISK_READ : SAMPLE_DEFAULT_METHOD_TMP,
	RATE_METRIC_DISK_WRITE : SAMPLE_DEFAULT_METHOD_TMP,
	RATE_METRIC_NETWORK_INGRESS : SAMPLE_DEFAULT_METHOD_TMP,
	RATE_METRIC_NETWORK_EGRESS : SAMPLE_DEFAULT_METHOD_TMP,
	RATE_METRIC_DISK_BYTESREAD : SAMPLE_DEFAULT_METHOD_TMP,
	RATE_METRIC_DISK_BYTESWRITE : SAMPLE_DEFAULT_METHOD_TMP,
	RATE_METRIC_NETWORK_BYTEINGRESS : SAMPLE_DEFAULT_METHOD_TMP,
	RATE_METRIC_NETWORK_BYTEEGRESS : SAMPLE_DEFAULT_METHOD_TMP,
}



type PrometheusRule struct {
	Groups []*PrometheusRuleGroupDetail `yaml:"groups"`
}

type PrometheusRuleGroupDetail struct{
	Name string `yaml:"name"`
	Rules []*PrometheusRuleDetail `yaml:"rules"`
}

type PrometheusRuleDetail struct{
	Alert string `yaml:"alert"`
	Expr string `yaml:"expr"`
	For string `yaml:"for"`
	Labels map[string]interface{} `yaml:"labels"`
	Annotations struct {
		Summary string `yaml:"summary"`
		Description string `yaml:"description"`
		CurrentValue string `yaml:"currentValue"`
	} `yaml:"annotations"`
}
