default bmp agent
    prompt 0
    timeout 1
    label bmp agent
    kernel ${BMP_KERNEL_PATH_x86}
    append initrd=${BMP_INITRAMFS_PATH_x86} net.ifnames=0 biosdevname=0 BMP_MQ_HOST=${BMP_HOST_IP} BMP_MQ_PORT=${BMP_MQ_PORT} BMP_MQ_USER=${BMP_MQ_USER} BMP_MQ_PASSWORD='${BMP_MQ_PASSWORD}' BMP_MQ_VHOST=${BMP_MQ_VHOST} BMP_MQ_EXCHANGE_ROUTING_KEY=${BMP_MQ_EXCHANGE_ROUTING_KEY} BMP_IMAGE_HOST=${BMP_HOST_IP} BMP_IMAGE_PORT=${BMP_IMAGE_PORT} BMP_RSYSLOG_HSOT=${BMP_HOST_IP} BMP_RSYSLOG_PORT=${BMP_RSYSLOG_PORT}