// Code generated by go-swagger; DO NOT EDIT.

package sshkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-console-sdk/models"
)

// ModifyUserSshkeyReader is a Reader for the ModifyUserSshkey structure.
type ModifyUserSshkeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyUserSshkeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModifyUserSshkeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewModifyUserSshkeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewModifyUserSshkeyOK creates a ModifyUserSshkeyOK with default headers values
func NewModifyUserSshkeyOK() *ModifyUserSshkeyOK {
	return &ModifyUserSshkeyOK{}
}

/* ModifyUserSshkeyOK describes a response with status code 200, with default header values.

A ModifyUserSshkeyResult is an response struct that is used to modify sshkey result.
*/
type ModifyUserSshkeyOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *ModifyUserSshkeyOKBody
}

// IsSuccess returns true when this modify user sshkey o k response has a 2xx status code
func (o *ModifyUserSshkeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this modify user sshkey o k response has a 3xx status code
func (o *ModifyUserSshkeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify user sshkey o k response has a 4xx status code
func (o *ModifyUserSshkeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this modify user sshkey o k response has a 5xx status code
func (o *ModifyUserSshkeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this modify user sshkey o k response a status code equal to that given
func (o *ModifyUserSshkeyOK) IsCode(code int) bool {
	return code == 200
}

func (o *ModifyUserSshkeyOK) Error() string {
	return fmt.Sprintf("[PUT /user/sshkeys/{sshkey_id}][%d] modifyUserSshkeyOK  %+v", 200, o.Payload)
}

func (o *ModifyUserSshkeyOK) String() string {
	return fmt.Sprintf("[PUT /user/sshkeys/{sshkey_id}][%d] modifyUserSshkeyOK  %+v", 200, o.Payload)
}

func (o *ModifyUserSshkeyOK) GetPayload() *ModifyUserSshkeyOKBody {
	return o.Payload
}

func (o *ModifyUserSshkeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(ModifyUserSshkeyOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyUserSshkeyDefault creates a ModifyUserSshkeyDefault with default headers values
func NewModifyUserSshkeyDefault(code int) *ModifyUserSshkeyDefault {
	return &ModifyUserSshkeyDefault{
		_statusCode: code,
	}
}

/* ModifyUserSshkeyDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type ModifyUserSshkeyDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *ModifyUserSshkeyDefaultBody
}

// Code gets the status code for the modify user sshkey default response
func (o *ModifyUserSshkeyDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this modify user sshkey default response has a 2xx status code
func (o *ModifyUserSshkeyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this modify user sshkey default response has a 3xx status code
func (o *ModifyUserSshkeyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this modify user sshkey default response has a 4xx status code
func (o *ModifyUserSshkeyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this modify user sshkey default response has a 5xx status code
func (o *ModifyUserSshkeyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this modify user sshkey default response a status code equal to that given
func (o *ModifyUserSshkeyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ModifyUserSshkeyDefault) Error() string {
	return fmt.Sprintf("[PUT /user/sshkeys/{sshkey_id}][%d] modifyUserSshkey default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyUserSshkeyDefault) String() string {
	return fmt.Sprintf("[PUT /user/sshkeys/{sshkey_id}][%d] modifyUserSshkey default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyUserSshkeyDefault) GetPayload() *ModifyUserSshkeyDefaultBody {
	return o.Payload
}

func (o *ModifyUserSshkeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(ModifyUserSshkeyDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ModifyUserSshkeyDefaultBody modify user sshkey default body
swagger:model ModifyUserSshkeyDefaultBody
*/
type ModifyUserSshkeyDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this modify user sshkey default body
func (o *ModifyUserSshkeyDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyUserSshkeyDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("modifyUserSshkey default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *ModifyUserSshkeyDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("modifyUserSshkey default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyUserSshkey default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyUserSshkey default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this modify user sshkey default body based on the context it is used
func (o *ModifyUserSshkeyDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyUserSshkeyDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyUserSshkey default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyUserSshkey default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ModifyUserSshkeyDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyUserSshkeyDefaultBody) UnmarshalBinary(b []byte) error {
	var res ModifyUserSshkeyDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ModifyUserSshkeyOKBody modify user sshkey o k body
swagger:model ModifyUserSshkeyOKBody
*/
type ModifyUserSshkeyOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this modify user sshkey o k body
func (o *ModifyUserSshkeyOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyUserSshkeyOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyUserSshkeyOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyUserSshkeyOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this modify user sshkey o k body based on the context it is used
func (o *ModifyUserSshkeyOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyUserSshkeyOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyUserSshkeyOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyUserSshkeyOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ModifyUserSshkeyOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyUserSshkeyOKBody) UnmarshalBinary(b []byte) error {
	var res ModifyUserSshkeyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
