package TimezoneLogic

import (
	"coding.jd.com/aidc-bmp/bmp-operation-api/constant"
	responseTypes "coding.jd.com/aidc-bmp/bmp-operation-api/types/response"
	log "git.jd.com/cps-golang/log"
)

var TimeZoneDictZh responseTypes.OrderedJsonDict = responseTypes.OrderedJsonDict{
	M: map[string]string{
		"Pacific/Pago_Pago":      "(GMT-11:00)帕果帕果",
		"US/Hawaii":              "(GMT-10:00)夏威夷时间",
		"US/Pacific":             "(GMT-08:00)太平洋时间",
		"America/Tijuana":        "(GMT-08:00)太平洋时间-提华纳",
		"US/Mountain":            "(GMT-07:00)山区时间",
		"US/Arizona":             "(GMT-07:00)山区时间-亚利桑那州",
		"America/Chihuahua":      "(GMT-07:00)山区时间-奇瓦瓦，马萨特兰",
		"US/Central":             "(GMT-07:00)中部时间",
		"America/Mexico_City":    "(GMT-06:00)中部时间-墨西哥城",
		"America/Regina":         "(GMT-06:00)中部时间-里贾纳",
		"America/Guatemala":      "(GMT-06:00)中部时间-里贾纳",
		"America/Bogota":         "(GMT-05:00)波哥大",
		"US/Eastern":             "(GMT-05:00)东部时间",
		"America/Lima":           "(GMT-05:00)利马",
		"America/Caracas":        "(GMT-04:30)加拉加斯",
		"America/Halifax":        "(GMT-04:00)大西洋时间-哈利法克斯",
		"America/Guyana":         "(GMT-04:00)圭亚那",
		"America/La_Paz":         "(GMT-04:00)拉巴斯",
		"America/Buenos_Aires":   "(GMT-03:00)布宜诺斯艾利斯",
		"America/Godthab":        "(GMT-03:00)戈特霍布",
		"America/Montevideo":     "(GMT-03:00)蒙得维的亚",
		"Canada/Newfoundland":    "(GMT-03:30)纽芬兰时间-圣约翰",
		"America/Santiago":       "(GMT-03:00)圣地亚哥",
		"America/Sao_Paulo":      "(GMT-02:00)圣保罗",
		"Atlantic/South_Georgia": "(GMT-02:00)南乔治亚州",
		"Atlantic/Azores":        "(GMT-01:00)亚速尔群岛",
		"Atlantic/Cape_Verde":    "(GMT-01:00)佛得角",
		"Africa/Casablanca":      "(GMT+00:00)卡萨布兰卡",
		"Europe/Dublin":          "(GMT+00:00)都柏林",
		"Europe/Lisbon":          "(GMT+00:00)里斯本",
		"Europe/London":          "(GMT+00:00)伦敦",
		"Africa/Monrovia":        "(GMT+00:00)蒙罗维亚",
		"Africa/Algiers":         "(GMT+01:00)阿尔及尔",
		"Europe/Amsterdam":       "(GMT+01:00)阿姆斯特丹",
		"Europe/Berlin":          "(GMT+01:00)柏林",
		"Europe/Brussels":        "(GMT+01:00)布鲁塞尔",
		"Europe/Budapest":        "(GMT+01:00)布达佩斯",
		"Europe/Belgrade":        "(GMT+01:00)中欧时间-贝尔格莱德",
		"Europe/Prague":          "(GMT+01:00)中欧时间-布拉格",
		"Europe/Copenhagen":      "(GMT+01:00)哥本哈根",
		"Europe/Madrid":          "(GMT+01:00)马德里",
		"Europe/Paris":           "(GMT+01:00)巴黎",
		"Europe/Rome":            "(GMT+01:00)罗马",
		"Europe/Stockholm":       "(GMT+01:00)斯德哥尔摩",
		"Europe/Vienna":          "(GMT+01:00)维也纳",
		"Europe/Warsaw":          "(GMT+01:00)华沙",
		"Europe/Athens":          "(GMT+02:00)雅典",
		"Europe/Bucharest":       "(GMT+02:00)布加勒斯特",
		"Africa/Cairo":           "(GMT+02:00)开罗",
		"Europe/Helsinki":        "(GMT+02:00)赫尔辛基",
		"Asia/Jerusalem":         "(GMT+02:00)耶路撒冷",
		"Africa/Johannesburg":    "(GMT+02:00)约翰内斯堡",
		"Europe/Kiev":            "(GMT+02:00)基辅",
		"Europe/Kaliningrad":     "(GMT+02:00)莫斯科-加里宁格勒",
		"Europe/Riga":            "(GMT+02:00)里加",
		"Europe/Sofia":           "(GMT+02:00)索非亚",
		"Europe/Tallinn":         "(GMT+02:00)塔林",
		"Europe/Vilnius":         "(GMT+02:00)维尔纽斯",
		"Asia/Baghdad":           "(GMT+03:00)巴格达",
		"Asia/Istanbul":          "(GMT+03:00)伊斯坦布尔",
		"Europe/Minsk":           "(GMT+03:00)明斯克",
		"Asia/Riyadh":            "(GMT+03:00)利雅得",
		"Europe/Moscow":          "(GMT+03:00)莫斯科-莫斯科",
		"Asia/Tehran":            "(GMT+03:30)德黑兰",
		"Asia/Baku":              "(GMT+04:00)巴库",
		"Europe/Samara":          "(GMT+04:00)莫斯科-萨马拉",
		"Asia/Tbilisi":           "(GMT+04:00)第比利斯",
		"Asia/Yerevan":           "(GMT+04:00)埃里温",
		"Asia/Kabul":             "(GMT+04:30)喀布尔",
		"Asia/Karachi":           "(GMT+05:00)卡拉奇",
		"Asia/Yekaterinburg":     "(GMT+05:00)莫斯科-叶卡捷琳堡",
		"Asia/Tashkent":          "(GMT+05:00)塔什干",
		"Asia/Colombo":           "(GMT+05:30)科伦坡",
		"Asia/Almaty":            "(GMT+06:00)阿拉木图",
		"Asia/Dhaka":             "(GMT+06:00)达卡",
		"Asia/Rangoon":           "(GMT+06:30)仰光",
		"Asia/Bangkok":           "(GMT+07:00)曼谷",
		"Asia/Jakarta":           "(GMT+07:00)雅加达",
		"Asia/Krasnoyarsk":       "(GMT+07:00)莫斯科-克拉斯诺亚尔斯克",
		"Asia/Shanghai":          "(GMT+08:00)中国时间-北京",
		"Hongkong":               "(GMT+08:00)香港",
		"Asia/Kuala_Lumpur":      "(GMT+08:00)吉隆坡",
		"Asia/Irkutsk":           "(GMT+08:00)莫斯科-伊尔库茨克",
		"Asia/Singapore":         "(GMT+08:00)新加坡",
		"Asia/Taipei":            "(GMT+08:00)台北",
		"Asia/Ulaanbaatar":       "(GMT+08:00)乌兰巴托",
		"Australia/Perth":        "(GMT+08:00)西部时间-珀斯",
		"Asia/Yakutsk":           "(GMT+09:00)莫斯科-雅库茨克",
		"Asia/Seoul":             "(GMT+09:00)首尔",
		"Asia/Tokyo":             "(GMT+09:00)东京",
		"Australia/Darwin":       "(GMT+09:30)中部时间-达尔文",
		"Australia/Brisbane":     "(GMT+10:00)东部时间-布里斯班",
		"Pacific/Guam":           "(GMT+10:00)关岛",
		"Asia/Magadan":           "(GMT+10:00)莫斯科-马加丹",
		"Asia/Sakhalin":          "(GMT+10:00)莫斯科-南萨哈林斯克",
		"Pacific/Port_Moresby":   "(GMT+10:00)莫尔兹比港",
		"Australia/Adelaide":     "(GMT+10:30)中部时间-阿德莱德",
		"Australia/Hobart":       "(GMT+11:00)东部时间-霍巴特",
		"Australia/Melbourne":    "(GMT+11:00)东部时间-悉尼墨尔本",
		"Pacific/Guadalcanal":    "(GMT+11:00)Guadalcanal",
		"Pacific/Noumea":         "(GMT+11:00)努美阿",
		"Pacific/Majuro":         "(GMT+12:00)马朱罗",
		"Asia/Kamchatka":         "(GMT+12:00)莫斯科-堪察加彼得罗巴甫洛夫斯克",
		"Pacific/Auckland":       "(GMT+13:00)奥克兰",
		"Pacific/Fakaofo":        "(GMT+13:00)法考福",
		"Pacific/Fiji":           "(GMT+13:00)斐济",
		"Pacific/Tongatapu":      "(GMT+13:00)汤加塔布群岛",
		"Pacific/Apia":           "(GMT+14:00)阿皮亚",
	},
	Keys: []string{"Pacific/Pago_Pago", "US/Hawaii", "US/Pacific", "America/Tijuana", "US/Mountain", "US/Arizona", "America/Chihuahua", "US/Central", "America/Mexico_City", "America/Regina", "America/Guatemala", "America/Bogota", "US/Eastern", "America/Lima", "America/Caracas", "America/Halifax", "America/Guyana", "America/La_Paz", "America/Buenos_Aires", "America/Godthab", "America/Montevideo", "Canada/Newfoundland", "America/Santiago", "America/Sao_Paulo", "Atlantic/South_Georgia", "Atlantic/Azores", "Atlantic/Cape_Verde", "Africa/Casablanca", "Europe/Dublin", "Europe/Lisbon", "Europe/London", "Africa/Monrovia", "Africa/Algiers", "Europe/Amsterdam", "Europe/Berlin", "Europe/Brussels", "Europe/Budapest", "Europe/Belgrade", "Europe/Prague", "Europe/Copenhagen", "Europe/Madrid", "Europe/Paris", "Europe/Rome", "Europe/Stockholm", "Europe/Vienna", "Europe/Warsaw", "Europe/Athens", "Europe/Bucharest", "Africa/Cairo", "Europe/Helsinki", "Asia/Jerusalem", "Africa/Johannesburg", "Europe/Kiev", "Europe/Kaliningrad", "Europe/Riga", "Europe/Sofia", "Europe/Tallinn", "Europe/Vilnius", "Asia/Baghdad", "Asia/Istanbul", "Europe/Minsk", "Asia/Riyadh", "Europe/Moscow", "Asia/Tehran", "Asia/Baku", "Europe/Samara", "Asia/Tbilisi", "Asia/Yerevan", "Asia/Kabul", "Asia/Karachi", "Asia/Yekaterinburg", "Asia/Tashkent", "Asia/Colombo", "Asia/Almaty", "Asia/Dhaka", "Asia/Rangoon", "Asia/Bangkok", "Asia/Jakarta", "Asia/Krasnoyarsk", "Asia/Shanghai", "Hongkong", "Asia/Kuala_Lumpur", "Asia/Irkutsk", "Asia/Singapore", "Asia/Taipei", "Asia/Ulaanbaatar", "Australia/Perth", "Asia/Yakutsk", "Asia/Seoul", "Asia/Tokyo", "Australia/Darwin", "Australia/Brisbane", "Pacific/Guam", "Asia/Magadan", "Asia/Sakhalin", "Pacific/Port_Moresby", "Australia/Adelaide", "Australia/Hobart", "Australia/Melbourne", "Pacific/Guadalcanal", "Pacific/Noumea", "Pacific/Majuro", "Asia/Kamchatka", "Pacific/Auckland", "Pacific/Fakaofo", "Pacific/Fiji", "Pacific/Tongatapu", "Pacific/Apia"},
}

var TimeZoneDictEn responseTypes.OrderedJsonDict = responseTypes.OrderedJsonDict{
	M: map[string]string{
		"Pacific/Pago_Pago":      "(GMT-11:00) Pago Pago",
		"US/Hawaii":              "(GMT-10:00) Hawaii Time",
		"US/Pacific":             "(GMT-08:00) Pacific Time",
		"America/Tijuana":        "(GMT-08:00) Pacific Time - Tijuana",
		"US/Mountain":            "(GMT-07:00) Mountain Time",
		"US/Arizona":             "(GMT-07:00) Mountain Time - Arizona",
		"America/Chihuahua":      "(GMT-07:00) Mountain Time - Chihuahua, Mazatlan",
		"US/Central":             "(GMT-06:00) Central Time",
		"America/Mexico_City":    "(GMT-06:00) Central Time - Mexico City",
		"America/Regina":         "(GMT-06:00) Central Time - Regina",
		"America/Guatemala":      "(GMT-06:00) Guatemala",
		"America/Bogota":         "(GMT-05:00) Bogota",
		"US/Eastern":             "(GMT-05:00) Eastern Time",
		"America/Lima":           "(GMT-05:00) Lima",
		"America/Caracas":        "(GMT-04:30) Caracas",
		"America/Halifax":        "(GMT-04:00) Atlantic Time - Halifax",
		"America/Guyana":         "(GMT-04:00) Guyana",
		"America/La_Paz":         "(GMT-04:00) La Paz",
		"America/Buenos_Aires":   "(GMT-03:00) Buenos Aires",
		"America/Godthab":        "(GMT-03:00) Godthab",
		"America/Montevideo":     "(GMT-03:00) Montevideo",
		"Canada/Newfoundland":    "(GMT-03:30) Newfoundland Time - St. Johns",
		"America/Santiago":       "(GMT-03:00) Santiago",
		"America/Sao_Paulo":      "(GMT-02:00) Sao Paulo",
		"Atlantic/South_Georgia": "(GMT-02:00) South Georgia",
		"Atlantic/Azores":        "(GMT-01:00) Azores",
		"Atlantic/Cape_Verde":    "(GMT-01:00) Cape Verde",
		"Africa/Casablanca":      "(GMT+00:00) Casablanca",
		"Europe/Dublin":          "(GMT+00:00) Dublin",
		"Europe/Lisbon":          "(GMT+00:00) Lisbon",
		"Europe/London":          "(GMT+00:00) London",
		"Africa/Monrovia":        "(GMT+00:00) Monrovia",
		"Africa/Algiers":         "(GMT+01:00) Algiers",
		"Europe/Amsterdam":       "(GMT+01:00) Amsterdam",
		"Europe/Berlin":          "(GMT+01:00) Berlin",
		"Europe/Brussels":        "(GMT+01:00) Brussels",
		"Europe/Budapest":        "(GMT+01:00) Budapest",
		"Europe/Belgrade":        "(GMT+01:00) Central European Time - Belgrade",
		"Europe/Prague":          "(GMT+01:00) Central European Time - Prague",
		"Europe/Copenhagen":      "(GMT+01:00) Copenhagen",
		"Europe/Madrid":          "(GMT+01:00) Madrid",
		"Europe/Paris":           "(GMT+01:00) Paris",
		"Europe/Rome":            "(GMT+01:00) Rome",
		"Europe/Stockholm":       "(GMT+01:00) Stockholm",
		"Europe/Vienna":          "(GMT+01:00) Vienna",
		"Europe/Warsaw":          "(GMT+01:00) Warsaw",
		"Europe/Athens":          "(GMT+02:00) Athens",
		"Europe/Bucharest":       "(GMT+02:00) Bucharest",
		"Africa/Cairo":           "(GMT+02:00) Cairo",
		"Europe/Helsinki":        "(GMT+02:00) Helsinki",
		"Asia/Jerusalem":         "(GMT+02:00) Jerusalem",
		"Africa/Johannesburg":    "(GMT+02:00) Johannesburg",
		"Europe/Kiev":            "(GMT+02:00) Kiev",
		"Europe/Kaliningrad":     "(GMT+02:00) Moscow-01 - Kaliningrad",
		"Europe/Riga":            "(GMT+02:00) Riga",
		"Europe/Sofia":           "(GMT+02:00) Sofia",
		"Europe/Tallinn":         "(GMT+02:00) Tallinn",
		"Europe/Vilnius":         "(GMT+02:00) Vilnius",
		"Asia/Baghdad":           "(GMT+03:00) Baghdad",
		"Asia/Istanbul":          "(GMT+03:00) Istanbul",
		"Europe/Minsk":           "(GMT+03:00) Minsk",
		"Asia/Riyadh":            "(GMT+03:00) Riyadh",
		"Europe/Moscow":          "(GMT+03:00) Moscow+00 - Moscow",
		"Asia/Tehran":            "(GMT+03:30) Tehran",
		"Asia/Baku":              "(GMT+04:00) Baku",
		"Europe/Samara":          "(GMT+04:00) Moscow+01 - Samara",
		"Asia/Tbilisi":           "(GMT+04:00) Tbilisi",
		"Asia/Yerevan":           "(GMT+04:00) Yerevan",
		"Asia/Kabul":             "(GMT+04:30) Kabul",
		"Asia/Karachi":           "(GMT+05:00) Karachi",
		"Asia/Yekaterinburg":     "(GMT+05:00) Moscow+02 - Yekaterinburg",
		"Asia/Tashkent":          "(GMT+05:00) Tashkent",
		"Asia/Colombo":           "(GMT+05:30) Colombo",
		"Asia/Almaty":            "(GMT+06:00) Almaty",
		"Asia/Dhaka":             "(GMT+06:00) Dhaka",
		"Asia/Rangoon":           "(GMT+06:30) Rangoon",
		"Asia/Bangkok":           "(GMT+07:00) Bangkok",
		"Asia/Jakarta":           "(GMT+07:00) Jakarta",
		"Asia/Krasnoyarsk":       "(GMT+07:00) Moscow+04 - Krasnoyarsk",
		"Asia/Shanghai":          "(GMT+08:00) China Time - Beijing",
		"Hongkong":               "(GMT+08:00) Hong Kong",
		"Asia/Kuala_Lumpur":      "(GMT+08:00) Kuala Lumpur",
		"Asia/Irkutsk":           "(GMT+08:00) Moscow+05 - Irkutsk",
		"Asia/Singapore":         "(GMT+08:00) Singapore",
		"Asia/Taipei":            "(GMT+08:00) Taipei",
		"Asia/Ulaanbaatar":       "(GMT+08:00) Ulaanbaatar",
		"Australia/Perth":        "(GMT+08:00) Western Time - Perth",
		"Asia/Yakutsk":           "(GMT+09:00) Moscow+06 - Yakutsk",
		"Asia/Seoul":             "(GMT+09:00) Seoul",
		"Asia/Tokyo":             "(GMT+09:00) Tokyo",
		"Australia/Darwin":       "(GMT+09:30) Central Time - Darwin",
		"Australia/Brisbane":     "(GMT+10:00) Eastern Time - Brisbane",
		"Pacific/Guam":           "(GMT+10:00) Guam",
		"Asia/Magadan":           "(GMT+10:00) Moscow+07 - Magadan",
		"Asia/Sakhalin":          "(GMT+10:00) Moscow+07 - Yuzhno-Sakhalinsk",
		"Pacific/Port_Moresby":   "(GMT+10:00) Port Moresby",
		"Australia/Adelaide":     "(GMT+10:30) Central Time - Adelaide",
		"Australia/Hobart":       "(GMT+11:00) Eastern Time - Hobart",
		"Australia/Melbourne":    "(GMT+11:00) Eastern Time - Melbourne, Sydney",
		"Pacific/Guadalcanal":    "(GMT+11:00) Guadalcanal",
		"Pacific/Noumea":         "(GMT+11:00) Noumea",
		"Pacific/Majuro":         "(GMT+12:00) Majuro",
		"Asia/Kamchatka":         "(GMT+12:00) Moscow+09 - Petropavlovsk-Kamchatskiy",
		"Pacific/Auckland":       "(GMT+13:00) Auckland",
		"Pacific/Fakaofo":        "(GMT+13:00) Fakaofo",
		"Pacific/Fiji":           "(GMT+13:00) Fiji",
		"Pacific/Tongatapu":      "(GMT+13:00) Tongatapu",
		"Pacific/Apia":           "(GMT+14:00) Apia",
	},
	Keys: []string{"Pacific/Pago_Pago", "US/Hawaii", "US/Pacific", "America/Tijuana", "US/Mountain", "US/Arizona", "America/Chihuahua", "US/Central", "America/Mexico_City", "America/Regina", "America/Guatemala", "America/Bogota", "US/Eastern", "America/Lima", "America/Caracas", "America/Halifax", "America/Guyana", "America/La_Paz", "America/Buenos_Aires", "America/Godthab", "America/Montevideo", "Canada/Newfoundland", "America/Santiago", "America/Sao_Paulo", "Atlantic/South_Georgia", "Atlantic/Azores", "Atlantic/Cape_Verde", "Africa/Casablanca", "Europe/Dublin", "Europe/Lisbon", "Europe/London", "Africa/Monrovia", "Africa/Algiers", "Europe/Amsterdam", "Europe/Berlin", "Europe/Brussels", "Europe/Budapest", "Europe/Belgrade", "Europe/Prague", "Europe/Copenhagen", "Europe/Madrid", "Europe/Paris", "Europe/Rome", "Europe/Stockholm", "Europe/Vienna", "Europe/Warsaw", "Europe/Athens", "Europe/Bucharest", "Africa/Cairo", "Europe/Helsinki", "Asia/Jerusalem", "Africa/Johannesburg", "Europe/Kiev", "Europe/Kaliningrad", "Europe/Riga", "Europe/Sofia", "Europe/Tallinn", "Europe/Vilnius", "Asia/Baghdad", "Asia/Istanbul", "Europe/Minsk", "Asia/Riyadh", "Europe/Moscow", "Asia/Tehran", "Asia/Baku", "Europe/Samara", "Asia/Tbilisi", "Asia/Yerevan", "Asia/Kabul", "Asia/Karachi", "Asia/Yekaterinburg", "Asia/Tashkent", "Asia/Colombo", "Asia/Almaty", "Asia/Dhaka", "Asia/Rangoon", "Asia/Bangkok", "Asia/Jakarta", "Asia/Krasnoyarsk", "Asia/Shanghai", "Hongkong", "Asia/Kuala_Lumpur", "Asia/Irkutsk", "Asia/Singapore", "Asia/Taipei", "Asia/Ulaanbaatar", "Australia/Perth", "Asia/Yakutsk", "Asia/Seoul", "Asia/Tokyo", "Australia/Darwin", "Australia/Brisbane", "Pacific/Guam", "Asia/Magadan", "Asia/Sakhalin", "Pacific/Port_Moresby", "Australia/Adelaide", "Australia/Hobart", "Australia/Melbourne", "Pacific/Guadalcanal", "Pacific/Noumea", "Pacific/Majuro", "Asia/Kamchatka", "Pacific/Auckland", "Pacific/Fakaofo", "Pacific/Fiji", "Pacific/Tongatapu", "Pacific/Apia"},
}

func GetTimeZoneList(logger *log.Logger) responseTypes.OrderedJsonDict {

	language := logger.GetPoint("language").(string)
	if language == constant.LANGUAGE_EN {
		return TimeZoneDictEn
	} else {
		return TimeZoneDictZh
	}
}
