// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveDeviceParams creates a new RemoveDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveDeviceParams() *RemoveDeviceParams {
	return &RemoveDeviceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveDeviceParamsWithTimeout creates a new RemoveDeviceParams object
// with the ability to set a timeout on a request.
func NewRemoveDeviceParamsWithTimeout(timeout time.Duration) *RemoveDeviceParams {
	return &RemoveDeviceParams{
		timeout: timeout,
	}
}

// NewRemoveDeviceParamsWithContext creates a new RemoveDeviceParams object
// with the ability to set a context for a request.
func NewRemoveDeviceParamsWithContext(ctx context.Context) *RemoveDeviceParams {
	return &RemoveDeviceParams{
		Context: ctx,
	}
}

// NewRemoveDeviceParamsWithHTTPClient creates a new RemoveDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveDeviceParamsWithHTTPClient(client *http.Client) *RemoveDeviceParams {
	return &RemoveDeviceParams{
		HTTPClient: client,
	}
}

/* RemoveDeviceParams contains all the parameters to send to the API endpoint
   for the remove device operation.

   Typically these are written to a http.Request.
*/
type RemoveDeviceParams struct {

	/* Authorization.

	   demo: curl -X GET -H "Authorization:Bearer wwabmrpdxz04qa10frpuw7key9qkd9bu" http://127.0.0.1:8801/v1/idcs 请使用个人自己创建apikey时候的token
	*/
	Authorization string

	/* BmpLanguage.

	   用户语言 [zh_CN, en_US]
	*/
	BmpLanguage *string

	/* BmpUserID.

	   用户uuid
	*/
	BmpUserID *string

	// DeviceID.
	DeviceID string

	/* TraceID.

	   流量唯一id
	*/
	TraceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveDeviceParams) WithDefaults() *RemoveDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove device params
func (o *RemoveDeviceParams) WithTimeout(timeout time.Duration) *RemoveDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove device params
func (o *RemoveDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove device params
func (o *RemoveDeviceParams) WithContext(ctx context.Context) *RemoveDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove device params
func (o *RemoveDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove device params
func (o *RemoveDeviceParams) WithHTTPClient(client *http.Client) *RemoveDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove device params
func (o *RemoveDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the remove device params
func (o *RemoveDeviceParams) WithAuthorization(authorization string) *RemoveDeviceParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the remove device params
func (o *RemoveDeviceParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBmpLanguage adds the bmpLanguage to the remove device params
func (o *RemoveDeviceParams) WithBmpLanguage(bmpLanguage *string) *RemoveDeviceParams {
	o.SetBmpLanguage(bmpLanguage)
	return o
}

// SetBmpLanguage adds the bmpLanguage to the remove device params
func (o *RemoveDeviceParams) SetBmpLanguage(bmpLanguage *string) {
	o.BmpLanguage = bmpLanguage
}

// WithBmpUserID adds the bmpUserID to the remove device params
func (o *RemoveDeviceParams) WithBmpUserID(bmpUserID *string) *RemoveDeviceParams {
	o.SetBmpUserID(bmpUserID)
	return o
}

// SetBmpUserID adds the bmpUserId to the remove device params
func (o *RemoveDeviceParams) SetBmpUserID(bmpUserID *string) {
	o.BmpUserID = bmpUserID
}

// WithDeviceID adds the deviceID to the remove device params
func (o *RemoveDeviceParams) WithDeviceID(deviceID string) *RemoveDeviceParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the remove device params
func (o *RemoveDeviceParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithTraceID adds the traceID to the remove device params
func (o *RemoveDeviceParams) WithTraceID(traceID string) *RemoveDeviceParams {
	o.SetTraceID(traceID)
	return o
}

// SetTraceID adds the traceId to the remove device params
func (o *RemoveDeviceParams) SetTraceID(traceID string) {
	o.TraceID = traceID
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param authorization
	if err := r.SetHeaderParam("authorization", o.Authorization); err != nil {
		return err
	}

	if o.BmpLanguage != nil {

		// header param bmpLanguage
		if err := r.SetHeaderParam("bmpLanguage", *o.BmpLanguage); err != nil {
			return err
		}
	}

	if o.BmpUserID != nil {

		// header param bmpUserId
		if err := r.SetHeaderParam("bmpUserId", *o.BmpUserID); err != nil {
			return err
		}
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// header param traceId
	if err := r.SetHeaderParam("traceId", o.TraceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
