// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"coding.jd.com/aidc-bmp/bmp-openapi-console-sdk/models"
)

// ModifyLocalUserReader is a Reader for the ModifyLocalUser structure.
type ModifyLocalUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyLocalUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModifyLocalUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewModifyLocalUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewModifyLocalUserOK creates a ModifyLocalUserOK with default headers values
func NewModifyLocalUserOK() *ModifyLocalUserOK {
	return &ModifyLocalUserOK{}
}

/* ModifyLocalUserOK describes a response with status code 200, with default header values.

A ModifyLocalUserResult is an response struct that is used to describe getuser.
*/
type ModifyLocalUserOK struct {

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *ModifyLocalUserOKBody
}

// IsSuccess returns true when this modify local user o k response has a 2xx status code
func (o *ModifyLocalUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this modify local user o k response has a 3xx status code
func (o *ModifyLocalUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify local user o k response has a 4xx status code
func (o *ModifyLocalUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this modify local user o k response has a 5xx status code
func (o *ModifyLocalUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this modify local user o k response a status code equal to that given
func (o *ModifyLocalUserOK) IsCode(code int) bool {
	return code == 200
}

func (o *ModifyLocalUserOK) Error() string {
	return fmt.Sprintf("[PUT /local/users][%d] modifyLocalUserOK  %+v", 200, o.Payload)
}

func (o *ModifyLocalUserOK) String() string {
	return fmt.Sprintf("[PUT /local/users][%d] modifyLocalUserOK  %+v", 200, o.Payload)
}

func (o *ModifyLocalUserOK) GetPayload() *ModifyLocalUserOKBody {
	return o.Payload
}

func (o *ModifyLocalUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(ModifyLocalUserOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyLocalUserDefault creates a ModifyLocalUserDefault with default headers values
func NewModifyLocalUserDefault(code int) *ModifyLocalUserDefault {
	return &ModifyLocalUserDefault{
		_statusCode: code,
	}
}

/* ModifyLocalUserDefault describes a response with status code -1, with default header values.

unit err response for non 200
*/
type ModifyLocalUserDefault struct {
	_statusCode int

	/* 流量ID
	in: header
	*/
	TraceID string

	Payload *ModifyLocalUserDefaultBody
}

// Code gets the status code for the modify local user default response
func (o *ModifyLocalUserDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this modify local user default response has a 2xx status code
func (o *ModifyLocalUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this modify local user default response has a 3xx status code
func (o *ModifyLocalUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this modify local user default response has a 4xx status code
func (o *ModifyLocalUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this modify local user default response has a 5xx status code
func (o *ModifyLocalUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this modify local user default response a status code equal to that given
func (o *ModifyLocalUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ModifyLocalUserDefault) Error() string {
	return fmt.Sprintf("[PUT /local/users][%d] modifyLocalUser default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyLocalUserDefault) String() string {
	return fmt.Sprintf("[PUT /local/users][%d] modifyLocalUser default  %+v", o._statusCode, o.Payload)
}

func (o *ModifyLocalUserDefault) GetPayload() *ModifyLocalUserDefaultBody {
	return o.Payload
}

func (o *ModifyLocalUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header traceId
	hdrTraceID := response.GetHeader("traceId")

	if hdrTraceID != "" {
		o.TraceID = hdrTraceID
	}

	o.Payload = new(ModifyLocalUserDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ModifyLocalUserDefaultBody modify local user default body
swagger:model ModifyLocalUserDefaultBody
*/
type ModifyLocalUserDefaultBody struct {

	// 流量ID
	// Required: true
	RequestID *string `json:"requestId"`

	// error
	// Required: true
	Error *models.ErrorResponse `json:"error"`
}

// Validate validates this modify local user default body
func (o *ModifyLocalUserDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyLocalUserDefaultBody) validateRequestID(formats strfmt.Registry) error {

	if err := validate.Required("modifyLocalUser default"+"."+"requestId", "body", o.RequestID); err != nil {
		return err
	}

	return nil
}

func (o *ModifyLocalUserDefaultBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("modifyLocalUser default"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyLocalUser default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyLocalUser default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this modify local user default body based on the context it is used
func (o *ModifyLocalUserDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyLocalUserDefaultBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyLocalUser default" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyLocalUser default" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ModifyLocalUserDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyLocalUserDefaultBody) UnmarshalBinary(b []byte) error {
	var res ModifyLocalUserDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ModifyLocalUserOKBody modify local user o k body
swagger:model ModifyLocalUserOKBody
*/
type ModifyLocalUserOKBody struct {

	// result
	Result *models.CommonResponse `json:"result,omitempty"`
}

// Validate validates this modify local user o k body
func (o *ModifyLocalUserOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyLocalUserOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyLocalUserOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyLocalUserOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this modify local user o k body based on the context it is used
func (o *ModifyLocalUserOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyLocalUserOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modifyLocalUserOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modifyLocalUserOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ModifyLocalUserOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyLocalUserOKBody) UnmarshalBinary(b []byte) error {
	var res ModifyLocalUserOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
